# CHAPTER TWO: SAVORING THE MOMENT: A LINK BETWEEN AFFECTIVITY AND DEPRESSION
### Introduction
Affective theories of mood and anxiety disorders have posited that low positive affectivity is a specific risk factor for depression [@clarkTripartiteModelAnxiety1991; @lewinsohnPleasantActivitiesDepression1973; @watsonTestingTripartiteModel1995; @watsonTestingTripartiteModel1995a], whereas high negative affectivity may be a more general indicator of distress that is observed across depression and anxiety disorders, as well as other psychopathology types [@watsonNegativeAffectivityDisposition1984]. Positive affectivity reflects a tendency to experience intense and frequent episodes of pleasant moods [@watsonPositiveAffectivity2009], while negative affectivity refers to a tendency to experience negative moods [@watsonNegativeAffectivityDisposition1984]. 
Positive and negative affectivity are theorized to represent stable individual differences indicative of an individual’s disposition to experience positive and negative affect (i.e., transient emotional experiences) respectively. To this extent, positive affectivity and negative affectivity are closely associated with highly stable personality traits such as extraversion and neuroticism, correspondingly [@costaInfluenceExtraversionNeuroticism1980; @warrIndependencePositiveNegative1983]. While certain major life events (e.g., unemployment, disability) are associated with long-term changes in subjective well-being, others (e.g., marriage, widowhood, divorce) only have short-term effects with a tendency to revert back to baseline levels of positive affectivity following these major events [@lucasAdaptationSetpointModel2007a; @suhEventsSubjectiveWellbeing1996; @watsonPositiveAffectivity2009]. With regard to depression, the frequency of positive life events is not fully explanatory of depression symptoms [@needlesPositiveLifeEvents1990]. Rather, the relationship between positive events and depression symptomatology is likely modulated by individual differences ranging from cognitive style [@needlesPositiveLifeEvents1990] to neurobiological factors [@watsonPositiveAffectivity2009] that influence the interpretation and/or experience of positive events. Related, research has indicated that emotional inertia (i.e., degree to which one’s affective state is predicted by a previous affective state) may be a risk factor for future development of mood disorders [@kovalGettingStuckDepression2012; @kuppensEmotionalInertiaPsychological2010]. Research has also concurrently indicated that affective instability is related to depression symptoms [@thompsonEverydayEmotionalExperience2012]. Seeking to reconcile these findings, research utilizing experience sampling and controlled laboratory methods found that more resistant negative emotion, specifically, was related to depression while positive emotion continues to fluctuate [@kovalAffectDynamicsRelation2013a]. While research has explored the role of negative emotion regulation strategies [e.g., reappraisal, acceptance, problem solving; @aldaoEmotionregulationStrategiesPsychopathology2010a] in the context of depression, the same cannot be said about positive emotion regulation [@siltonRegulatingPositiveEmotions2020a]. Characterizing specific positive emotion regulation strategies that mediate the relationship between affectivity and depression could inform treatment and intervention approaches to depression.   

### Emotion Regulation and Depression
The connection between negative emotion regulation and depression is well established [@grossEmergingFieldEmotion1998; @grossEmotionRegulationMental1995; @joormannEmotionRegulationDepression2010; @joormannEmotionRegulationDepression2014; @nolen-hoeksemaResponseStylesDuration1993]. Individuals with depression are more likely to engage in maladaptive regulation strategies such as rumination, expressive suppression, and catastrophizing and less likely to utilize adaptive strategies like reappraisal and self-disclosure compared to individuals without depression [@garnefskiCognitiveEmotionRegulation2007; @grossIndividualDifferencesTwo2003; @joormannEmotionRegulationDepression2010]. More recently, research has begun to examine the influence of positive emotion regulation on depression symptoms [@feldmanResponsesPositiveAffect2008; @nelisResponseStylesPositive2015; @raesDampeningPositiveAffect2012; @werner-seidlerInvestigationRelationshipPositive2013]. Beck [-@beckCognitiveTherapyEmotional1979] theorized that dampening positive emotions intensifies and perpetuates depression. Accordingly, greater dampening of positive affect is prospectively associated with increased depression symptoms three and five months later [@raesDampeningPositiveAffect2012]. Other research has shown that those with depression tend to be apprehensive about experiencing positive affect and thus engage in maladaptive emotion regulation strategies, such as dampening positive affect [@werner-seidlerInvestigationRelationshipPositive2013]. Furthermore, Werner-Seidler et al. [-@werner-seidlerInvestigationRelationshipPositive2013] showed that depression symptoms are inversely related to strategies implemented to amplify positive affect and depression. In sum, although research is beginning to establish that those with depression tend to engage in maladaptive positive emotion regulation strategies that reduce positive emotion [@carlPositiveEmotionRegulation2013; @garnefskiCognitiveEmotionRegulation2007; @grossEmotionRegulationTaking2013; @siltonRegulatingPositiveEmotions2020a], there has been less focus on identifying strategies that may successfully enhance positive emotion in individuals who are at risk for depression. As such, the present study evaluates the hypothesis that savoring may ameliorate depression symptoms.

### Savoring Responses and Savoring Beliefs
Savoring refers to an awareness of positive experiences and the use of positive emotion regulation strategies to enhance and extend positive feelings that are derived from those experiences [@bryantFourfactorModelPerceived1989; @bryantSavoringNewModel2007; @bryantUnderstandingProcessesThat2011; @smithSavoringWellbeingMapping2017]. People initiate savoring responses in reaction to a positive event or affect as a way to maintain, intensify, or prolong positive experience [@bryantSavoringNewModel2007]. The original conceptual formulation of savoring [@bryantSavoringNewModel2007] is predicated on the theory that people typically engage in savoring responses in reaction to positive events or affect, which people regulate through cognitive or behavioral strategies. Chronically low levels of positive affectivity would be expected to reduce savoring responses, which over time would lower self-evaluations of savoring ability. While savoring, one may anticipate the enjoyments of future positive experiences, focus on ongoing positive experiences as they occur, or reminisce about past positive experiences. Regardless of the temporal focus, savoring processes regulate positive emotions in the present moment. 
In contrast to savoring responses, savoring beliefs are self-perceptions of one’s capacity to savor [@bryantSavoringBeliefsInventory2003a]. Although related to ways in which people regulate positive feelings in response to positive events, savoring beliefs are dispositional tendencies that are distinct from specific savoring strategies in which people engage. Stronger savoring beliefs are associated with lower levels of depression symptoms [@bryantSavoringBeliefsInventory2003a; @eisnerPositiveAffectRegulation2009; @houSavoringModeratesAssociation2016; @ramseyAgeDifferencesSubjective2014; @smithSavoringResiliencePsychological2015]. Examining the correlations between savoring beliefs and depression in two separate samples, Bryant (2003) found a significant negative correlation between savoring the moment and depression in both samples, a significant negative correlation between positive reminiscence and depression in one of the samples, and no correlation between positive anticipation and depression in either sample. In another study, savoring the moment, but not anticipation, was also identified as a unique predictor of lifetime depression symptoms [@carverTendenciesManiaTendencies2009]. These results suggest that the capacity to savor ongoing positive experiences as they occur may have the strongest relationship with level of depression symptoms. Furthermore, those endorsing higher levels of savoring beliefs report similar experiences as those endorsing high levels of positive affectivity—namely, intense and frequent episodes of positive affect [@bryantSavoringNewModel2007; @watsonPositiveAffectivity2009].

### Savoring and Positive Affect
Savoring strategies that amplify positive emotions are associated with greater frequency of positive affect [@gentzlerYoungAdolescentsResponses2013; @quoidbachPositiveEmotionRegulation2010; @smithNurturingCapacitySavor2014]. As an example, college students who reminisced for one week using either memorabilia or cognitive imagery reported greater increases in frequency of happy feelings compared to participants in a control condition [@bryantUsingEnhancePresent2005]. In addition, a present-focused savoring strategy, mindfully photographing beautiful or meaningful subjects, led to more positive moods compared to photographing neutral subjects [@kurtzSeeingNewEyes2015]. Research has also found that greater savoring beliefs are associated with higher intensity of positive affect and less negative affect [@bryantSavoringBeliefsInventory2003a; @smithAreWeHaving2013]. Across two separate samples, people who reported stronger savoring beliefs also tended to report higher levels of personality traits associated with increased positive affect, such as intensity of happy feelings, self-esteem, frequent happy feelings, and less frequent unhappy feelings [@bryantSavoringBeliefsInventory2003a]. Using experience sampling methodology, [-@joseDoesSavoringIncrease2012] found that momentary savoring mediated the relationship between daily positive events and momentary happiness, and this effect was stronger for people with higher trait levels of amplifying (i.e., broad types of savoring strategies) and weaker for people with higher trait levels of dampening. Research has also shown that a combination of low capacity to savor the moment and experiencing less positive events is most strongly associated with lower positive affect and less life satisfaction [@hurleySavoringHelpsMost2013; @joseDoesSavoringIncrease2012]. Collectively, these studies illustrate that higher savoring capacity results in greater frequency and intensity of positive affect, which is representative of elevated positive affectivity. However, while this research has investigated the relationship between savoring beliefs and trait-like attributes such as intensity and frequency of affect and increased self-esteem, previous research has not explicitly examined the relationship between trait affectivity and savoring beliefs within the context of depression. The present study evaluates savoring as a positive emotion regulation strategy that may modify low positive affectivity and thus reduce depression symptoms. 

### The Focus of the Present Study
A variety of interventions have been developed that focus on each of the three temporal domains of savoring (i.e., reminiscing, savoring the moment, and anticipating) in an effort to boost happiness [@smithNurturingCapacitySavor2014]. For example, cultivating the ability to imagine future positive events can enhance anticipating [@quoidbachBackFutureEffect2009], taking mindful photographs aids in momentary savoring [@kurtzSeeingNewEyes2015], and increasing awareness of recent positive events serves to bolster reminiscing [@seligmanPositivePsychologyProgress2005]. Thus, if savoring mediates the relationship between affectivity and depression, it may be an effective and modifiable target for bolstering positive affectivity and reducing depression symptoms. 
Common treatments for depression, including cognitive behavioral therapy (CBT) and antidepressant medication [@priceNeurocircuitryMoodDisorders2010a], leave considerable room for improvement that may be fulfilled by focusing on enhancing PA. These treatments predominantly focus on ameliorating distorted thought patterns and neurotransmitter systems pertaining to negative emotions [@argyropoulosAnhedoniaRevisitedThere2013; @beckCognitiveTherapyEmotional1979]. Approximately 45-65% of those with depression undergoing CBT do not achieve remission [@derubeisCognitiveTherapyVs2005; @dimidjianRandomizedTrialBehavioral2006]. The importance of enhancing PA is corroborated by the fact that patient definitions of depression recovery equally emphasize repair of PA and NA [@demyttenaereWhatImportantBeing2015]. Further, Dunn and colleagues [-@dunnChangesPositiveNegative2019] conducted two separate studies investigating the efficacy of therapeutic and pharmacological approaches to treating depression and mitigating high NA and PA. Results indicated that NA and PA were both uniquely related to depression and that current treatments (CBT, selective serotonin reuptake inhibitors, selective norepinephrine reuptake inhibitors, tricyclic antidepressants, and monoamine oxidase inhibitors) improve NA, but do little to bolster PA [@dunnChangesPositiveNegative2019]. This is despite the fact that reductions in PA were more marked than elevated NA in the samples tested, indicating that PA may be a more pressing intervention target [@dunnChangesPositiveNegative2019]. Novel treatments have theorized that increased use of dampening appraisals may be a psychological mechanism of reduced PA [@dunnTurningGoldLead2018]. This implicates positive emotion regulation and savoring, which is underscored by literature illustrating that greater savoring beliefs are correlated with lower levels of depressive symptoms [@bryantSavoringBeliefsInventory2003a; @eisnerPositiveAffectRegulation2009; @houSavoringModeratesAssociation2016; @ramseyAgeDifferencesSubjective2014; @smithSavoringResiliencePsychological2015]. A more thorough understanding of the mechanisms of PA and savoring may pave the way for improving depression treatments. 
The present study characterizes the relationship between affectivity, savoring beliefs, and depression symptomatology. We evaluated the following hypotheses: 1) replicating past research, positive affectivity will be negatively associated with depression symptoms and negative affectivity will be positively associated with depression symptoms, 2) positive affectivity will be positively associated with all three temporal domains of savoring and negative affectivity will be negatively associated with all three temporal domains of savoring, 3) savoring the moment will be distinctly associated with depression, and 4) savoring the moment will distinctly mediate the relationship between affectivity and depression. Despite the present study’s focus on PA, mitigating NA remains an important factor to address in depression, with research demonstrating that both are independently related to depression symptoms [@dunnChangesPositiveNegative2019]. Additionally, given the negative associations that exist between stable negative traits and savoring (e.g., neuroticism; Bryant, 2003), NA was included as an exogenous variable in the exploratory path analysis. Further, including NA facilitates the analysis of PA and NA’s unique relationship with depression via the temporal domains of savoring by statistically controlling for the effects of the other. Because anxiety and depression symptoms frequently co-occur [@americanpsychiatricassociationDiagnosticStatisticalManual2013a; @clarkAnxietyDepressiveDisorders1989; @minekaComorbidityAnxietyUnipolar1998], we accounted for the effects of anxiety by including measures of anxious arousal (somatic) and anxious apprehension (worry) symptoms [@sharpTransdiagnosticDimensionsAnxiety2015] in our analyses. Additionally, research suggests that worry spans temporal domains and is associated with rumination about past events and hopelessness regarding the future [@andrewsDifferentialEffectsInductions1988; @macleodAnxietyDepressionAnticipation1996] as well as procrastination [@stoberWorryProcrastinationPerfectionism2001], each of which may overlap with the temporal domains of savoring. Further, since research indicates that females tend to report greater savoring capacity than do males (Bryant & Veroff, 2007), gender was included as a covariate.
The present study utilized a parallel mediation model with cross-sectional data. Some researchers have advocated against this practice since correlational data do not afford causal interpretation [@maxwellBiasCrosssectionalAnalyses2011]. Alternatively, Hayes [-@hayesIntroductionMediationModeration2018] advocated for a more relaxed stance: “We should not let the limitations of our data collection efforts constrain the tools we bring to the task of trying to understand what our data might be telling us about the processes we are studying” (p. 18). Many researchers share this sentiment as indicated by their use of mediation analyses with cross-sectional data [@blashillRoleBodyImage2010; @gauntParentsInvolvementChildcare2014; @goodinPainCatastrophizingMediates2009; @kungCultureFixedworldBeliefs2016; @leeResilienceBuffersImpact2014; @liIncompatibilityMaterialismDesire2011; @osborneOrganizationalRespectDampens2015; @pollackModeratingRoleSocial2012; @reesSocialSupportModerates2009; @smithWeightGenderService2016; @thaiNeuralCorrelatesAttention2016; @thomasRejectionSensitivityAdjustment2015; @torresEthnicMicroaggressionsTraumatic2015; @webbYouBetterNot2016]. Thus, the present study utilized cross-sectional mediation analyses while recognizing its preclusion of causal inference.

## Method
### Participants
Participants (N = 2,482) were recruited from introductory psychology courses. Participants received course credit for completion of an online survey. Case wise deletion was used to omit participants (n  = 864) that had missing responses to any questionnaires used in the present study. The final sample of 1,618 participants (n = 375 males, n = 1,243 females) ranged in age from 17 - 40 (M = 18.99 years, SD = 1.33) and was 70.0% Caucasian, 19.1% Asian, 4.5% Black or African American, 0.9% Native Hawaiian or other Pacific Islander, 0.7% American Indian or Alaskan Native, and 4.9% Biracial; 11.4% reported that they were Hispanic/Latinx and 88.6% were not Hispanic/Latinx. The study was approved by the University’s Institutional Review Board, and informed consent was provided to all participants prior to beginning the survey.

### Questionnaire Measures
_Savoring capacity._ We administered the Savoring Beliefs Inventory (Bryant, 2003) to assess participants’ savoring capacity. The SBI measures the perception of one’s ability to feel pleasure through anticipating positive experiences, savoring positive moments as they occur, and reminiscing about past positive events (Bryant & Veroff, 2007). The SBI was analyzed as three eight-item subscales pertaining to temporal forms of savoring: anticipating (e.g., “Before a good thing happens, I look forward to it in ways that give me pleasure in the present.”), savoring the moment (e.g., “I know how to make the most of a good time.”), and reminiscing (e.g., “I enjoy looking back on happy times from my past.”). Items are rated on a seven-point Likert scale from “1” (strongly disagree) to “7” (strongly agree). The three temporal subscales of the SBI were originally conceived as separate, intercorrelated measures of individuals’ characteristic capacities to savor. Test-retest reliability assessments provide cross-cultural evidence for the stability of the SBI subscales (Bryant, 2003; Kawakubo, Bryant, Miyakawa, & Oguchi, 2019). Prospective research testing predictive validity found that participants’ SBI scores predicted ability to anticipate, momentarily savor, or reminisce upon winter break three months later (Bryant, 2003). This empirical evidence collectively supports the conclusion that the three SBI subscales reflect stable traits that manifest themselves in predictable forms of behavioral and emotion experience over time. Bryant (2003) found moderate to high internal consistency across all three subscales. The present study replicated these findings (Anticipating, $\omega = .87$; Savoring the Moment, $\omega = .85$; and Reminiscing, $\omega = .86$).
_Depression severity._  To evaluate depression severity, the nine-item Patient Health Questionnaire (PHQ-9; Kroenke et al., 2001) was administered. PHQ-9 items are scored from “0” (not at all) to “3” (nearly every day) and are based on the depression criteria from the Diagnostic and Statistical Manual of Mental Disorders, Fourth Edition. Internal consistency of the PHQ-9 in the present study ($\omega = .87$) was consistent with past research (Kroenke et al., 2001). 
_Affectivity and anxiety symptoms._ To assess for positive and negative affectivity as well as anxiety, the 39-item Mood and Anxiety Symptoms Questionnaire (Watson, Clark, et al., 1995; Watson, Weber, et al., 1995) was administered. The MASQ was analyzed as three separate subscales: the eight-item negative affectivity (NA) Scale (MASQ-NA8; e.g., “Felt withdrawn from other people”), the 14-item positive affectivity (PA) Scale (MASQ-PA14; e.g., “Felt cheerful”), and the 17-item Anxious Arousal Scale (MASQ-AA; e.g., “Startled easily”). Previous literature has supported these oblique factors in two independent samples of individuals at-risk for depression and anxiety (Kendall et al., 2015; Nitschke, Heller, Imig, McDonald, & Miller, 2001). Participants rated their affectivity and anxiety symptoms using a five-point Likert scale from “1” (not at all) to “5” (extremely). Consistent with previous research (Bredemeier et al., 2010), the MASQ scales demonstrated good to excellent internal consistency(MASQ-NA8, $\omega = .80$; MASQ-PA14, $\omega = .94$; and MASQ-AA, $\omega = .88$).
_Worry._ The 16-item Penn State Worry Questionnaire (Meyer, Miller, Metzger, & Borkovec, 1990) was used to assess for the trait of worrying. PSWQ items are rated on a five-point Likert scale from “1” (not at all typical) to “5” (very typical). Meyer and colleagues (1990) found a high degree of internal consistency in the PSWQ, and the present study found good consistency ($\omega = .87$). 

## Results
### Depression Severity
To provide clinically relevant descriptive information regarding depression severity in the sample, participants were categorized into five depression severity groups based on established PHQ-9 cutoff scores: minimal (1-4), mild (5-9), moderate (10-14), moderately severe (15-19), and severe (20-27; Kroenke et al., 2001). Group means, standard deviations, and reliability coefficients of primary variables of interest (PA, NA, and savoring the moment) were calculated for each of the depression severity groups (see Table 1). Pairwise t-test comparisons with Holm correction were conducted to assess mean differences between each depression group for PA, NA, and savoring the moment. Analyses indicated significant differences between all groups for all variables except for the difference in mean PA between moderately severe and severe depression groups.

### Correlations Among Study Variables
Pearson correlations were computed among the primary study variables (see Table 2). As expected, PA was positively associated with all temporal domains of savoring. NA, depression, and anxious arousal were negatively associated with all temporal savoring domains. All correlations were statistically significant.

### Positive Affectivity, Negative Affectivity, and Anxious Arousal as Predictors of Depression
The tripartite model posits that depression and anxiety have specific relations with three affective dimensions: PA, NA, and anxious arousal (Watson, Clark, et al., 1995; Watson, Weber, et al., 1995). Given the present study’s focus on PA and depression, we wanted to confirm the unique relation between each of these dimensions and depression symptoms in the present sample. Per the tripartite model, we anticipated that low levels of PA and high levels of NA would be positively associated with depression symptoms, and that anxious arousal would be unrelated to depression symptoms. Multiple regression analyses were conducted with PA, NA, and anxious arousal as predictors and depressions with no covariates. Diverging from the specific association between PA and depression proposed by Clark and Watson (1991, 1995a, 1995b), results from the test sample indicated that each of the predictors were uniquely associated with depression. NA [$b = .52,\ \beta = .55,\ t(1614) = 25.47,\ p < .001$] was the strongest predictor of depression, followed by anxious arousal [$b = .11,\ \beta = .21,\ t(1614) = 10.38,\ p < .001$], and lastly PA [$b = -.09,\ \beta = -.19,\ t(1614) = -10.55,\ p < .001$].

### Mediation Analyses
Path analyses were run in R (R Core Team, 2019) using the lavaan package (Rosseel, 2012) to assess the indirect effects of PA and NA on depression via three temporal domains of savoring capacity while accounting for the variance associated with gender, worry, and anxious arousal (see Figure 1). Exogenous variables (PA and NA) were allowed to correlate with one another, as were the residual variances of each of the temporal domains of savoring. Maximum likelihood estimation was used to estimate path coefficients, and bias-corrected bootstrap confidence intervals based on 10,000 bootstrap samples were used to estimate indirect effects of temporal domains of savoring between affectivity and depression. The fully saturated model contained 45 free parameters with zero degrees of freedom, resulting in perfect goodness of fit indices. Results (see Figure 1 and Table 3) showed that PA was associated with anticipating (standardized: $a_1 = .41$, unstandardized: $a_1 = .30$, $p < .001$), savoring the moment (standardized: $a_2 = .46$, unstandardized: $a_2 = .36$, $p < .001$), and reminiscing (standardized: $a_3 = .39$, unstandardized: $a_3 = .28$, $p < .001$). There were significant associations between NA and anticipating (standardized: $a_i = -.11$, unstandardized: $a_i = -.16$, $p < .001$), savoring the moment (standardized: $a_{ii} = -.29$, unstandardized: $a_{ii} = -.44$, $p < .001$), and reminiscing (standardized: $a_{iii} = -.16$, unstandardized: $a_{iii} = -.23$,  $p < .001$). Further, savoring the moment was related to lower depression severity (standardized: $b_2 = -.07$, unstandardized: $b_2 = -.04$, $p = .024$), while anticipating and reminiscing were not. Bias-corrected bootstrap confidence intervals (based on 10,000 bootstrap samples; see Table 3) for the indirect effects of temporal domains of savoring between PA and depression did not include zero for savoring the moment (95% CI [-.028, -.002], $a_2b_2 = -.01$) but did include zero for anticipating (95% CI [-.009, .012], $a_1b_1 = .00$) and reminiscing (95% CI [-.009, .013], $a_3b_3 = .00$). Similarly, bias-corrected bootstrap confidence intervals for the indirect effects of temporal domains of savoring between NA and depression did not include zero for savoring the moment (95% CI [.003, .035], $a_{ii}b_2 = .02$) but did include zero for anticipating (95% CI [-.007, .005], $a_ib_1 = .00$) and reminiscing (95% CI [-.011, .007], $a_{iii}b_3 = .00$). Notably, there is a negative indirect effect between PA and depression via savoring the moment with a positive relationship between PA and savoring the moment. This signifies that the positive association between PA and momentary savoring results in reduced depression scores that accounts for a portion of the significant negative relationship between PA and depression (standardized: $c’_{PA} = -.16$, unstandardized: $c’_{PA} = -.08$, $p < .001$). The direct effect of NA on depression was also significant (standardized: $c’_{NA} = .49$, unstandardized: $c’_{NA} = .02$, $p < .001$).

## Discussion
The present study examined the relationship between affectivity (PA and NA) and depression symptoms via the future-, present-, and past-focused temporal domains of savoring beliefs (i.e., self-reported capacity to savor by anticipating, savor the moment, and savor by reminiscing, respectively). As predicted, results showed that PA and NA were associated with all three temporal domains of savoring. Savoring the moment distinctly mediated the relationship between affectivity and depression; whereas, the other temporal domains did not mediate this relationship. Replicating past research, we also found a relationship between affectivity and depression symptoms (Chorpita, 2002; Clark & Watson, 1991; Dunn et al., 2019; Khazanov & Ruscio, 2016; Watson, Clark, et al., 1995; Watson, Clark, & Carey, 1988; Watson, Weber, et al., 1995). Of note, we found that the effect size for the bivariate relationship between NA and depression (i.e., 55% shared variance) was roughly three times larger than the effect size for the relationship between PA and depression (i.e., 18% shared variance); but given that NA is theorized to be a common factor shared among depression and anxiety (Watson, Clark, et al., 1995; Watson, Weber, et al., 1995), higher NA may also be increased due to co-occurring anxiety symptoms. These findings are similar to results from a meta-analysis suggesting that low positive emotionality creates an inherent vulnerability to depression, but perhaps to a lesser degree than previously surmised (Khazanov & Ruscio, 2016).
While findings from the present study imply that structured interventions aimed at enhancing any of the three temporal domains of savoring may serve to attenuate levels of NA and bolster levels of PA and well-being, only savoring the moment is likely to reduce depression symptoms. This latter finding is consistent with previous research showing that momentary savoring capacity has a stronger negative association with depressive symptoms than do reminiscing and anticipating (Bryant, 2003; Carver & Johnson, 2009). Together, these findings indicate that developing interventions to promote savoring the moment may be effective in reducing depression. 
When partitioned by pre-established depression severity cutoff-scores (Kroenke et al., 2001), the majority of the sample fell into minimal and mild depression groups, with significantly fewer participants in the moderate to severe groups. This result is consistent with a previous study conducted by Kroenke and colleagues (2001) that categorized a sample of 580 adult participants into groups based on PHQ-9 depression cut-off scores. It is also critical to note that 444 participants (27.5%) of the total present sample likely meet clinical criteria for a depression diagnosis as indicated by scoring 10 or higher on the PHQ-9 (Kroenke et al., 2001). Additionally, pairwise comparisons indicate that as participants increase in depression severity, levels of PA and capacity to savor the moment decrease while NA increases. This supports a dimensional conceptualization of the relationship between depression symptoms and individual difference factors, the present study indicates that a gradual decrease in PA/savoring the moment and increase in NA accompany a rise in depression severity. 
The present study expands on previous research that has investigated the relationship between positive emotion regulation and depression by assessing beliefs about positive emotion regulation, specifically savoring, across past, present, and future temporal domains. As such, these findings suggest that savoring the moment, as opposed to reminiscing or anticipating, may be instrumental in bolstering PA and reducing NA to ameliorate depression symptoms. This conclusion is further supported by positive psychological interventions that include training in momentary savoring strategies to reduce depression (Hurley & Kwon, 2013; McMakin, Siegle, & Shirk, 2011; Smith & Hanni, 2019). In particular, a savoring-based intervention that instructed female college students with symptoms of dysphoria to make positive self-attributions for recent positive events was effective in reducing depression symptoms and sustaining positive affect following positive events (McMakin et al., 2011). In another study, participants who received training in the use of strategies for savoring the moment, such as memory building and expressing positive emotions, displayed lower depression and lower negative affect after two weeks compared to a control group (Hurley & Kwon, 2013). While interventions targeting reminiscing and anticipating may serve to increase PA and decrease NA, patients presenting with depression may require more specific treatment focused on savoring the present moment compared to a non-clinical sample. Supporting this notion, increased attention to positive stimuli is likely one mechanism through which savoring influences depression symptoms (Carl et al., 2013). Although it should be noted that savoring and mindfulness are not analogous (Bryant & Veroff, 2007), the importance of moment-to-moment awareness in treating depression is corroborated by mindfulness-based interventions (Gu, Strauss, Bond, & Cavanagh, 2015).

### Limitations
The present study has several limitations. First, the present results are based solely on self-report measures. Although self-report data are often inordinately criticized (Chan, 2009), such measures are not without problems. Self-report methods are prone to exaggeration or underreporting, both of which may be caused by social desirability bias, or a tendency to present oneself favorably (Fisher, 1993). While the PHQ-9 is frequently used to screen for depression and track treatment outcomes in research studies and clinical settings, the present study did not implement clinical interviews to validate the self-report data. Future research in this area might consider using a clinical interview to confirm depression diagnoses. However, the PHQ-9 allows for a dimensional conceptualization of depression symptoms, which is likely to be more consistent with the range of affective and cognitive experiences that co-vary with depression symptoms (Levin et al., 2007).
Second, the present study is limited by its cross-sectional design, which precludes unequivocal conclusions about cause and effect. To overcome this limitation, future research should aim to extend the present findings using a longitudinal, randomized control trial (RCT) design to evaluate the impact of various savoring interventions designed to specifically target each of the three temporal domains in a sample of participants with low levels of PA and depression. In addition, more research is needed to understand the extent to which mindfulness-based interventions that focus on developing moment-to-moment awareness also indirectly enhance positive emotion regulation and savoring the moment, or whether interventions specifically designed to enhance savoring of positive events in the moment effectively reduce depression. Additionally, all subscales (anticipating, savoring the moment, reminiscing) measure one’s capacity to generate positive feelings in the moment while focusing on either past, present, or future positive experiences (Bryant & Veroff, 2007). Studies utilizing experience sampling methods (e.g., Koval et al., 2013) offer stronger conclusions regarding temporal fluctuations of emotion and depression symptoms.
The presence of multicollinearity, or tautological logic, can be argued due to the high correlation between NA and depression in the present sample and the fact that depressed mood (NA) forms a central construct of depression. Other researchers analyzing the association between affectivity (measured with the MASQ) and depression concluded that tautological logic did not compromise their analyses (Dunn et al., 2019). Additionally, the constructs of NA and depression are theoretically distinct despite being related. NA is conceptualized as a general indicator of distress observed across depression, anxiety, and other psychopathology types (Watson & Clark, 1984). It is conceptually disparate from positive emotions; one with high NA does not necessarily also lack joy, excitement, or enthusiasm, which are hallmarks of depression (Watson & Clark, 1984). Nitschke and colleagues (2001) corroborated this conceptualization via factor analysis, illustrating that the MASQ-NA subscale overlaps with anxiety and depression factors. Other research indicates that the MASQ-PA scale is a superior means of screening for depression compared to the MASQ-NA scale, further suggesting that NA is conceptually distinct from depression (Bredemeier et al., 2010). The PHQ-9, on the other hand, was designed to map onto criteria for major depressive disorder diagnosis in the Diagnostic and Statistical Manual of Mental Disorders (Kroenke & Spitzer, 2002). As such, the PHQ-9 was formulated for use in clinical settings with robust diagnostic sensitivity (Kroenke & Spitzer, 2001, 2002). Nonetheless, further clarification on the overlap between affectivity and depression are grounds for future research.
Finally, a post-hoc power analysis—using the bmem package (Zhang, 2014), specifying 1,000 Monte Carlo simulations, each with 1,000 bootstrap samples—indicated that the present sample provided less than optimal statistical power. In particular, our present sample (N = 1,618) yielded 60.5% power to detect a significant indirect effect of savoring the moment between PA/NA and depression via bootstrapping. Further analyses indicated that a sample size of 2,700 is required in order to reach 80% power for these indirect effects. This latter finding underscores the fact that researchers need to recruit large sample sizes to detect significant effects in complex mediation models.

### Conclusion
This is one of the first studies to examine the degree to which the three temporal domains of savoring mediate the relationship between affectivity and depression symptoms. Interventions that focus on bolstering any of the temporal domains of savoring may benefit those with low PA or high NA. However, enhancing momentary savoring may be the critical temporal domain to consider adapting as an intervention to ameliorate depression. Overall, our results suggest that interventions targeting positive emotion regulation may have considerable benefit for clinical and non-clinical populations. In advancing this research, RCT methodology should be implemented to confirm causality and benefit among individuals with depression disorders.

### Acknowledgments
	The authors thank the anonymous reviewers whose thoughtful feedback was instrumental in improving the quality of this manuscript. 
