# THE NEUROBIOLOGICAL CORRELATES OF SAVORING

### Positive Affectivity Influences Wellbeing
Positive affectivity (PA) refers to one's disposition to experience positive affect, or more transient positive emotions (e.g., happiness, interest, energy, and self-assurance) and level of pleasurable engagement with one's environment; [@watsonPositiveAffectivity2009; @watsonPositiveNegativeAffectivity1988; @watsonSpecificityPositiveEmotional2010b] and is theorized to represent a stable individual difference. PA may be a key variable influencing overall wellbeing, and strong links have been found between PA and health [@cohenPositiveAffectHealth2006]. In the famous nun study, Danner, Snowdon, & Friesen [-@dannerPositiveEmotionsEarly2001] demonstrated a strong inverse relationship between positive emotional content written in personal autobiographies (e.g., “emotion sentences” coded for affective states such as happiness, love, gratefulness, etc.) and mortality, above and beyond the influence of negative emotional content. Other studies also indicate that PA is related to lower rates of strokes among the elderly [@ostirAssociationEmotionalWellbeing2001]. Those reporting a greater tendency to experience positive affect also may have increased resilience to the common cold, even after accounting for the effects associated with negative affect [@cohenEmotionalStyleSusceptibility2003]. Research has shown that those suffering from life-threatening disease with decent prospects of survival (e.g., AIDS, coronary heart disease, early-stage breast cancer) show an association between PA and improved health outcomes [@pressmanDoesPositiveAffect2005a]. Higher levels of PA have also been associated with improved sleep quality, more exercise, and lower levels of the stress hormones epinephrine, norepinephrine, and cortisol [@cohenPositiveAffectHealth2006]. Additionally, PA has been hypothesized to increase levels of hormones and neurotransmitters, such as oxytocin and growth hormone, as well as endogenous opioids [@pressmanDoesPositiveAffect2005a]. PA also promotes prosocial behavior, empathy, forming closer relationships, and larger social networks [@morelliNeuralComponentsEmpathy2014], which are factors that positively impact overall health outcomes [@cacioppoLonelinessHealthPotential2002; @cohenPositiveAffectHealth2006].

While NA is a more general indicator of distress observed across depressive and anxiety disorder and associated with somatic symptoms [@minekaComorbidityAnxietyUnipolar1998; @watsonNegativeAffectivityDisposition1984], low PA is theroized be a unique risk factor for depression [@clarkTripartiteModelAnxiety1991; @kendallProspectiveAssociationsLow2015; @lewinsohnPleasantActivitiesDepression1973; @raesDampeningPositiveAffect2012; @watsonTestingTripartiteModel1995; @watsonTestingTripartiteModel1995a]. As such, low PA is associated with compounded depression symptoms [@clarkTripartiteModelAnxiety1991; @davidsonAffectiveStyleAffective1998; @watsonExtraversionPsychopathologyFacetlevel2015]. Indeed, Indeed, those with depression report reduced mood shifting in response to positive film clips, as well as an attenuated startle response (theorized to be an indicator of emotional reactivity) to positive and negative film clips [@kavianiAffectiveModulationStartle2004]. Underscording its trait-like nature, PA is resistant to most major life events influencing wellbeing; there is a tendency to revert back to baseline levels of PA in the long term [@suhEventsSubjectiveWellbeing1996; @watsonPositiveAffectivity2009]. Related, the presence of positive life events alone do not modify depressive symptoms [@needlesPositiveLifeEvents1990]. Possible mechanisms between the relationship between depression and the interpretation and experience of positive events include cognitive style [@needlesPositiveLifeEvents1990] and neural factors [@watsonPositiveAffectivity2009]. As such, advancing the neuroscientific understanding of state and trait positive affect has the potential to facilitate the development of intervention strategies that promote wellbeing for individuals with psychological and medical disorders.

### Neural Correlates of Positive Affectivity
Research has indicated that individuals self-described as happy tend to exhibit more left prefrontal cortical brain activity during resting state, while those endorsing dysphoria show greater right anterior frontal activity [@davidsonAnteriorAsymmetryNature1992; @tomarkenFrontalBrainAsymmetry1998]. Left prefrontal cortex (LPFC) activity is theorized to be related to the mesolimbic dopaminergic system, which is involved in subjective experiences of positive affect and reward-seeking [@burgdorfNeurobiologyPositiveEmotions2006a; @depueDopamineStructurePersonality1994; @depueNeurobiologyStructurePersonality1999] and marked by an asymmetric concentration of projections in the left frontal region. Related, research has indicated that dopaminergic activity is uniquely associated with positive affectivity [@depueDopamineStructurePersonality1994].

Research investigating neural responses to affective stimuli using functional magnetic resonance imaging (fMRI) indicates enhanced blood-oxygenation-level-dependent (BOLD) changes predominately in the right occipital cortex [i.e., fusiform cortex, lateral occipital cortex, & medial parietal cortex; @bradleyActivationVisualCortex2003], as well as the amygdala and visual cortex [@sabatinelliParallelAmygdalaInferotemporal2005] in response to affective (pleasant and unpleasant) compared to neutral images. These BOLD signal changes are correlated with emotional arousal ratings of affective stimuli, irrespective of valence. Indeed, the greatest changes in brain activity are observed for highly arousing stimuli, such as mutilations, erotica, and threat, compared to neutral objects [@bradleyBrainPotentialsPerception2007].

Researchers have posited that individuals who self-report higher levels of positive affectivity may gain more pleasure and exhibit more responsivity to positive stimuli [@grossRelationsAffectPersonality1998; @rustingExtraversionNeuroticismSuceptibility1997]. Previous research investigating the relationship between the personality traits and response to emotional stimuli examined extraversion and neuroticism which are closely related to PA and NA, respectively [@costaInfluenceExtraversionNeuroticism1980; @warrIndependencePositiveNegative1983]. Extraversion is defined as a personality trait associated with sociability, warmth, involvement with people, social participation, activity, and contributes to one’s enjoyment and satisfaction of life [@costaInfluenceExtraversionNeuroticism1980]. Neuroticism is associated with proneness to guilt, anxiety, psychosomatic concerns, worry, and may predispose one to suffer more from one’s misfortunes [@costaInfluenceExtraversionNeuroticism1980]. Gross and colleagues @grossRelationsAffectPersonality1998 observed a positive relationship between extraversion and increases in state positive affect after viewing a positive film clip. No relationship was found between extraversion and changes in state negative affect after viewing a negative film clip [@grossRelationsAffectPersonality1998]. Thus, those reporting higher positive affectivity may be deriving more pleasure from positive stimuli, which is consistent with reports of more frequent and intense episodes from those endorsing higher levels of positive affectivity [@watsonPositiveAffectivity2009]. These results are also in line with the notion that low levels of extraversion and neuroticism do not appear to reduce unpleasantness of adverse circumstances and diminish joy, respectively [@costaInfluenceExtraversionNeuroticism1980]. Overall, this suggests that extraversion and neuroticism may have distinct effects on relatively dissociable affective systems.

Canli and colleagues [-@canliFMRIStudyPersonality2001] investigated the relationship between stable personality traits (extraversion and neuroticism) and neural activation in response to positive and negative emotional stimuli. Extraversion scores correlated with brain activation in response to positive (relative to negative) pictures in bilateral cortical (frontal and temporal) and subcortical (e.g., amygdala, dorsal striatum) regions. Neuroticism, on the other hand, correlated with brain activation to negative (relative to positive) images in left temporal and frontal lobes [@canliFMRIStudyPersonality2001]. No correlations were found between extraversion and neural activation in response to negative (relative to positive) pictures [@canliFMRIStudyPersonality2001]. Another related study found that left amygdala activation in response to happy faces was positively correlated with extraversion scores [@canliAmygdalaResponseHappy2002], collectively suggesting that personality traits are associated with affective neural reactivity. These data are consistent with behavioral accounts demonstrating an association between positive emotional reactivity and extraversion [@grossFacetsEmotionalExpressivity1995]. Positive affectivity is highly correlated with extraversion [@costaInfluenceExtraversionNeuroticism1980] and positive is also marked by more intense episodes of positive affect [@watsonPositiveAffectivity2009]. Thus, it can be hypothesized that those with higher levels of positive affectivity may exhibit similar neural affective responsivity.

fMRI methodology has advanced the identification of specific subcortical structures involved in emotion, but its low temporal resolution precludes it from being an effective method of measuring neural time course [@kimLimitationsTemporalResolution1997]. In contrast, electroencephalography (EEG) allows for the analysis of event-related potentials (ERPs) that facilitate assessment of neural response to affective stimuli with millisecond temporal resolution [@olofssonAffectivePictureProcessing2008]. This is important considering the rapid processing of emotional stimuli that is characteristic of emotional responsivity [@olofssonAffectivePictureProcessing2008] and the perception of threatening/arousing events is enabled by a rapid processing pathway that recruits the thalamus and amygdala [@ledouxEmotionCircuitsBrain2000]. Thus, an improved understanding of the temporal course of ERPs evoked by affective stimuli will advance knowledge regarding affective processing [@battyEarlyProcessingSix2003; @codispotiRepetitionEventrelatedPotentials2007; @schuppEmotionAttentionEventrelated2006; @schuppStimulusNoveltyEmotion2006; @smithEventrelatedPotentialCorrelates2004].

Affective EEG research has implicated the late positive potential (LPP), a sustained positive slow wave observed starting as early as 300 ms following stimuli onset, as an established index of evaluative congruency, valence, and arousal in response to visual stimuli [@olofssonAffectivePictureProcessing2008]. Research has consistently shown that LPP activity over the centroparietal cortex are augmented in the presence of unpleasant and pleasant compared to neutral images [@cuthbertBrainPotentialsAffective2000; @dillonDissociationEventrelatedPotentials2006; @fotiDeconstructingReappraisalDescriptions2008; @hajcakAttendingAffectAppraisal2006; @hajcakReappraisalModulatesElectrocortical2006; @hajcakTemporalDynamicsEmotion2007; @keilLargescaleNeuralCorrelates2002; @moserIntentionalModulationEmotional2006; @olofssonAffectivePictureProcessing2008; @schuppEmotionalFacilitationSensory2003]. LPP activity is most pronounced for images that are rated as highly arousing [@bradleyInternationalAffectivePicture2007]. As such, LPP has been theorized to reflect activation of a brain network engaged in processing affective visual stimuli, including subcortical structures, particularly the amygdala [@bradleyInternationalAffectivePicture2007; @cuthbertBrainPotentialsAffective2000; @keilLargescaleNeuralCorrelates2002; @olofssonAffectivePictureProcessing2008; @schuppEmotionalFacilitationSensory2003]. Indeed, there is considerable input and output connections connecting the visual cortex to amygdaloid nuclei in primates [@amaralAnatomicalOrganizationPrimate1992]. LPP is theorized to index a visual cortical/amygdala pathway that is involved in evaluating the affective salience of stimuli [@sabatinelliEmotionalPerceptionCorrelation2007]. Several subcortical structures indirectly contribute to the scalp-recorded LPP component, and the extrastriate occipital, inferior temporal, and medial parietal cortex seem to be critical for the observation of LPP [@sabatinelliEmotionalPerceptionCorrelation2007]. LPP may index early processes associated with the salience network (SN) characterized by functional magnetic resonance imaging (fMRI) research. The SN refers to a network of brain regions of the medial wall of the frontal lobe, such as the anterior cingulate cortex and the presupplementary motor area, and the anterior insula [@beckmannInvestigationsRestingstateConnectivity2005; @seeleyDissociableIntrinsicConnectivity2007; @sridharanCriticalRoleRight2008] and is theorized to be important in assessing importance of internal and external stimuli in order to guide behavior [@seeleyDissociableIntrinsicConnectivity2007]. Nodes within the SN independently track feelings of pleasure and displeasure, as well as feelings of arousal in response to feelings of happiness, sadness, and fear [@barrettLargescaleBrainNetworks2013; @wilson-mendenhallNeuralEvidenceThat2013].

Much of the aforementioned research has utilized the International Affective Picture System [IAPS; @langInternationalAffectivePicture2008]. The IAPS is a set of color pictures that span a range of semantic categories, and valence/arousal ratings derived from a normative sample are provided for each image. The IAPS was developed to provide a standardized stimulus set of emotional images to facilitate the comparison of results across different studies, and enhance replication across research groups [@bradleyInternationalAffectivePicture2007]. IAPS images are rated with respect to valence (negative-to-positive) and arousal (low-to-high) on a nine-point visual analogue scale. The IAPS has been used in a number of studies investigating neural correlates of affective processing and emotion regulation [e.g., @fotiDeconstructingReappraisalDescriptions2008; @hajcakPersistenceAttentionEmotion2008; @hajcakReappraisalModulatesElectrocortical2006; @keilLargescaleNeuralCorrelates2002; @kimNeuralCorrelatesPositive2007; @moserIntentionalModulationEmotional2006; @olofssonAffectivePictureProcessing2008; @schuppEmotionalFacilitationSensory2003] and has aided in the advancement of affective science. However, the copyright agreement that accompanies the IAPS mandates that users cannot place any of the images on computer-accessible websites. This poses considerable restraint on increasing reliance on online samples in behavioral research that make data collection from large and diverse samples faster, less costly, and more efficient [@berinskyEvaluatingOnlineLabor2012; @buhrmesterAmazonMechanicalTurk2011; @krautPsychologicalResearchOnline2004; @masonConductingBehavioralResearch2012; @paolacciRunningExperimentsAmazon2010]. Thus, there is an increasing demand for images with standardized valence and arousal ratings for behavioral researchers to use in online contexts. Kurdi, Lazano, and Banaji [-@kurdiIntroducingOpenAffective2017] heeded this call with the Open Affective Standardized Image Set (OASIS). The OASIS is a collection of 900 high quality images collected from open-access online sources depicting a range of categories (people, animals, objects, & scenes). The OASIS was normed on valence and arousal ratings collected from a diverse sample recruited through Amazon’s Mechanical Turk [@kurdiIntroducingOpenAffective2017]. To the end of fulfilling Dr. Lang and Dr. Bradley’s vision of providing researchers experimental control in the selection of stimuli and facilitating comparison of results and replication across different studies, the present study utilized OASIS stimuli in lieu of the IAPS.

Replicating previous research on the neural time course of affective processing, it is expected that OASIS stimuli that are rated as more emotionally arousing will be associated with enhanced LPP activity for both positive and negative images compared to neutral images. Furthermore, given that a) positive affectivity is associated with greater frequency and intensity of positive affect, b) LPP is an established index of emotional arousal, and c) past research has indicated that neural responsivity to positive affective stimuli is correlated with extraversion, it is expected that higher self-reported positive affectivity will be associated with enhanced LPP activity in response to positive OASIS stimuli.

### Emotion Regulation and Savoring
Healthy emotion regulation abilities are integral to wellbeing [@grossEmergingFieldEmotion1998; @grossEmotionRegulationMental1995; @koolePsychologyEmotionRegulation2009; @sapolskyStressStressrelatedDisease2007]. Emotion regulation generally refers to individuals’ attempts to influence their emotional states [@carlPositiveEmotionRegulation2013], including modulation of positive and negative emotional states that are emotionally arousing [@koolePsychologyEmotionRegulation2009]. This also includes attenuating upsetting, or enhancing positive, aspects of a situation [@grossEmergingFieldEmotion1998]. Poor emotion regulation strategies are associated with reduced social functioning, such as avoidance of close relationships, few positive relationships, and disinclination to share emotions with others [@grossAntecedentandResponsefocusedEmotion1998; @grossEmotionRegulationAffective2002; @koolePsychologyEmotionRegulation2009], as well as lower self-esteem and life satisfaction [@grossAntecedentandResponsefocusedEmotion1998; @koolePsychologyEmotionRegulation2009; @ochsnerRethinkingFeelingsFMRI2002]. Poor emotion regulation is also associated with bullying and victimization among youth [@walcottRelationDisinhibitionEmotion2004], physical ailments such as hypertension and coronary heart disease [@hintonMechanismsEfficacyCBT2009; @jorgensenElevatedBloodPressure1996], exacerbated cortisol reactivity to stressors [@wirtzLowSocialSupport2006], and attenuated cognitive functioning [@keenanEmotionDysregulationRisk2000; @ochsnerRethinkingFeelingsFMRI2002].

While emotion regulation is often associated with decreasing negative emotion, it also pertains to increasing positive emotion, or savoring. Savoring refers to an awareness of positive experiences and the use of positive emotion regulation strategies to enhance and extend positive feelings that are derived from those experiences [@bryantFourfactorModelPerceived1989; @bryantSavoringBeliefsInventory2003a; @bryantSavoringNewModel2007; @bryantUnderstandingProcessesThat2011; @smithSavoringWellbeingMapping2017]. People initiate savoring responses in reaction to a positive event or affect as a way to maintain, intensify, or prolong the initial positive experience [@bryantSavoringNewModel2007]. The original conceptual formulation of savoring [@bryantSavoringNewModel2007] is predicated on the assumption that people typically initiate savoring responses in reaction to positive events or affect, which people regulate through cognitive or behavioral strategies. Chronically low levels or infrequency of positive affectivity would be expected to reduce savoring responses, which over time would lower self-evaluations of savoring ability. While savoring, one may reminisce about past positive experiences, focus on ongoing positive experiences as they occur, or anticipate the enjoyments of future positive experiences [@bryantSavoringNewModel2007]. Regardless of the temporal focus, savoring processes regulate positive emotions in the present moment.

Savoring is associated with a number of positive outcomes. Research has indicated that those with a greater capacity to savor possess increased life satisfaction, affective intensity, and self-esteem [@bryantUnderstandingProcessesThat2011]. Past research has also revealed that savoring is related to present happiness, total percent of time feeling happy versus sad, extraversion, optimism, and self-esteem. Furthermore, savoring is negatively associated with depression, neuroticism, and hopelessness [@bryantSavoringBeliefsInventory2003a; @eisnerPositiveAffectRegulation2009; @houSavoringModeratesAssociation2016; @ramseyAgeDifferencesSubjective2014; @smithSavoringResiliencePsychological2015]. A separate study found that savoring the moment is related to higher life satisfaction, subjective happiness, and overall higher levels of positive affect [@hurleyResultsStudyIncrease2012]. Other research has similarly revealed that savoring was strongly related to higher levels of present happiness, higher self-esteem, and lower reported levels of depression [@bryantSavoringBeliefsInventory2003a]. Furthermore, increased savoring capacity is associated with pain resilience [@thongBufferingRolePositive2016]. In sum, savoring may be a key mechanism in deriving vitality from our lives.

Savoring may have the potential to improve treatment of depression. 45-65% of those with depression undergoing common treatments for depression (e.g., cognitive behavioral therapy and psychotropics; @priceNeurocircuitryMoodDisorders2010a) do not achieve remission [@derubeisCognitiveTherapyVs2005]. These common treatments address distorted thought patterns and neurotransmitter systems associated with negative emotions [@argyropoulosAnhedoniaRevisitedThere2013; @beckCognitiveTherapyEmotional1979] despite the fact that patient definitions of of depression recovery emphasize repair of PA and NA equally [@demyttenaereWhatImportantBeing2015]. Additionally, research has shown that NA and PA are both uniquely associated with depression and that current treatments do little to bolster PA [@dunnChangesPositiveNegative2019]. Further, reductions in PA have been shown to be a more pressing intervention target for those with depression [@dunnChangesPositiveNegative2019]. The importance of positive emotion regulation in depression treatment is underscored by the fact that novel treatments have theorized that increased use of dampening appraisals may be a psychological mechanism of reduced PA [@dunnTurningGoldLead2018] and that greater levels of savoring beliefs are negatively associated with depression symptoms [@bryantSavoringBeliefsInventory2003a; @eisnerPositiveAffectRegulation2009; @houSavoringModeratesAssociation2016; @ramseyAgeDifferencesSubjective2014; @smithSavoringResiliencePsychological2015]. A more thorough understanding of the neural correlates of PA and savoring may facilitate neuroscience-informed clinical interventions aimed at increased savoring capacity and mitigating depression.

### Neural Correlates of Emotion Regulation
A general pattern of findings from fMRI research has illustrated an association between reappraisal of negative emotional stimuli and 1) activation of the dorsal anterior cingulate cortex (ACC) and prefrontal cortex (PFC) systems that are implicated in the selection and use of reappraisal strategies and 2) increases, decreases, or maintenance of activity in the amygdala or insula that is in accordance with the goal of reappraisal [@beauregardNeuralCorrelatesConscious2001; @levesqueNeuralCircuitryUnderlying2003; @ochsnerBetterWorseNeural2004; @ochsnerRethinkingFeelingsFMRI2002; @phanNeuralSubstratesVoluntary2005; @schaeferModulationAmygdalarActivity2002]. For example, Ochsner et al. [-@ochsnerBetterWorseNeural2004] analyzed brain structures correlated with reappraisal of negative images (to increase or decrease emotional significance of the image) via fMRI. Both up and down regulation strategies were associated with increased PFC and ACC activity, while amygdala activity increased or decreased in line with the regulatory goal [@ochsnerBetterWorseNeural2004]. Another study conducted by Beauregard and colleagues [-@beauregardNeuralCorrelatesConscious2001] similarly found that volitional inhibition of emotional arousal in response to erotic stimuli was associated with increased PFC and ACC activity and decreased amygdala activation compared to passively watching viewing stimuli.

One of the few studies that probed the neural correlates of positive emotion regulation examined fMRI BOLD response while participants increased and decreased emotional intensity in response to positive and negative images [@kimNeuralCorrelatesPositive2007]. Consistent with previous research, results of the study indicated that volitional emotion regulation modulated amygdala activity in both regulation conditions for positive and negative stimuli compared to watch conditions. More specifically, increasing emotional intensity showed a positive relationship in activation between the amygdala and structures (e.g., ACC and PFC) implicated in cognitive control. On the other hand, decreasing emotional intensity changed the direction of the relationship, with greater activation of cognitive control regions being related to attenuated amygdala activity [@kimNeuralCorrelatesPositive2007].

The aforementioned fMRI studies have focused on identifying specific brain regions involved in emotion regulation by examining static portraits of BOLD signals accumulating over the course of several seconds. Tracking how neural activation unfolds and changes over time is essential in better characterizing the process of emotion regulation and delineating which structures activate concomitantly with reactive and regulatory processes [@hajcakTemporalDynamicsEmotion2007]. To this end of characterizing the processing stages, or neural time course, of emotion regulation, EEG is an ideal method to use since it measures near-instantaneous activity of cortical activation [@hajcakTemporalDynamicsEmotion2007].

As previously mentioned, LPP is theorized to index a visual cortical/amygdala pathway that is involved in evaluating the affective salience of stimuli  [@sabatinelliParallelAmygdalaInferotemporal2005]. Thus, it could be reasonably hypothesized that the aforementioned fMRI research would translate to modulation of LPP signals dependent on the appraisal of emotional stimuli. Research has supported this claim. One study conducted by Foti & Hajcak  [-@fotiDeconstructingReappraisalDescriptions2008] examined changes in LPP activity when negative images were preceded by more or less negative descriptions. When unpleasant pictures were explained more neutrally, resulting LPP activity were reduced compared to unpleasant pictures that were described negatively [@fotiDeconstructingReappraisalDescriptions2008]. In a similar vein, one study compared LPP activity in affective and non-affective appraisal conditions of emotional stimuli. In the non-affective condition, participants were instructed to report the number of people were in each image. During affective conditions, participants rated images as pleasant or unpleasant. Compared to the affective condition, LPP was reliably reduced in the non-affective condition for positive and negative stimuli [@hajcakAttendingAffectAppraisal2006]. Collectively, these studies illustrate that LPP is not only sensitive to the emotional content of stimuli, but also how the stimuli are appraised.

These aforementioned studies have indeed illustrated that LPP activity can be modulated, but what of more deliberate regulation strategies akin to savoring? @moserIntentionalModulationEmotional2006 asked participants to deliberately suppress or enhance emotional intensity in response to high arousing negative and neutral images. A passive viewing, or “watch” condition was also included. Participants’ LPP activity were significantly smaller when suppressing emotional response to negative images compared to passively watching them. A notable finding of this study was that there were no observed differences in LPP between passive watch and enhance conditions. The authors attribute this to a number of factors, one of which was the utilization of only unpleasant images. Using pleasant images, they argue, may produce an augmented LPP in the enhance condition.

In response, @krompingerModulationsElectrophysiologicalResponse2008 analyzed LPP signals in response to increasing and decreasing emotional responses to, as well as passively watching, positive images. Results indicated increased LPP signals in response to passively watching positive stimuli compared to neutral stimuli. Furthermore, LPP signals were attenuated when participants were instructed to suppress emotional response vs. passively watch. However, no significant differences were found for the enhance condition [@krompingerModulationsElectrophysiologicalResponse2008]. The authors noted several limitations of this experiment, such as a relatively short stimulus duration compared to other studies (500 vs. 2000-6000 ms) that successfully captured emotional enhancement of affective stimuli [@ochsnerBetterWorseNeural2004]. Furthermore, this study did not collect self-report trait data. Considering that past research has found correlations between personality trait measures and neural activation in response to emotional stimuli [@canliAmygdalaResponseHappy2002; @canliFMRIStudyPersonality2001], a trait measure specifically measuring the regulation of positive emotion (i.e., savoring beliefs) may explain additional variance that is not being accounted for.  

Research collectively suggests that LPP may be an appropriate measure of the interaction between affective and cognitive processing [@moserIntentionalModulationEmotional2006]. Savoring is a type of emotion regulation that may be related to structures implicated in metacognition (e.g., ACC and PFC). Since a) LPP may be an indicator of this cognitive-affective interaction, b) LPP is an index of emotional arousal, and c) savoring is an emotion regulation strategy associated with increased emotional arousal in response to positive affect/events, it is hypothesized that the relationship between increasing emotional arousal in response to positive images and LPP will be dependent on one’s capacity to savor. More specifically, LPP may be modulated when increasing emotional intensity in response to positive stimuli, and this relationship is expected to be moderated by savoring capacity.

### The present study
Past research utilizing EEG has indicated that higher arousal in response to stimuli yields augmented LPP signals [@cuthbertBrainPotentialsAffective2000; @hajcakReappraisalModulatesElectrocortical2006; @schuppAffectivePictureProcessing2000; @thiruchselvamTemporalDynamicsEmotion2011; @trittIdeologicalReactivityPolitical2016]. Increasing emotional intensity results in enhanced amygdala activity and structures related to cognitive control [@kimNeuralCorrelatesPositive2007]. fMRI research has demonstrated that personality trait ratings (extraversion and neuroticism) correlate with neural responsivity to affective stimuli [@canliAmygdalaResponseHappy2002; @canliFMRIStudyPersonality2001]. Given that positive affectivity and extraversion are associated with more positive emotional arousal, it was hypothesized that the relationship between LPP signals and viewing positive stimuli will be dependent upon levels of positive affectivity. LPP is theorized to be indicative of an interaction between amygdala and cognitive control structures [@moserIntentionalModulationEmotional2006]. Furthermore, savoring capacity is positively associated with affect intensity and is indicative of one’s ability to bolster positive emotion [@bryantSavoringBeliefsInventory2003a]. Thus, savoring may be related to activation of neural structures associated with cognitive control. Therefore, higher self-report ratings of one’s capacity to savor were expected to moderate the relationship between LPP signals and increased emotional intensity in response to positive stimuli. 

The present study had two primary objectives. The first objective of the proposed study was to investigate the relationship between highly arousing affective vs. neutral OASIS stimuli and parietal cortical activity (LPP). It was hypothesized that a) highly arousing positive vs. neutral OASIS stimuli would be associated with greater LPP activity and b) highly arousing negative vs. neutral OASIS stimuli would be associated with greater LPP activity. The second objective was to examine the relationship between personality traits pertaining to positive emotion and LPP activity. It was predicted that a) positive affectivity would moderate the relationship between watching positive images and LPP activity and b) savoring capacity would moderate the relationship between increasing emotional intensity in response to positive images and LPP activity.

### Exploratory analyses
The aforementioned aims and hypotheses were preregistered (link: [https://osf.io/p5ba9/](https://osf.io/p5ba9/)). Post hoc exploratory analyses were also conducted. In addition to the LPP, the early posterior negativity (EPN) has also been found to be modulated by emotional valence of stimuli [@schuppAffectivePictureProcessing2012]. The EPN has been observed as a relative negative difference for stimuli as emotionally arousing/valenced compared to neutral stimuli in the 200 - 300 ms window over bilateral occipital-parietal sites [@olofssonAffectivePictureProcessing2008; @schuppAffectivePictureProcessing2000; @schuppAttentionEmotionERP2003] with potential resources residing in the occipital cortex with contributions from parietal regions [@wiensNonemotionalFeaturesSuppress2011]. For example, Yoon et al. [-@yoonEnhancedEarlyPosterior2016] found that EPN in response to happy and fearful faces were augmented compared to neutral faces among healthy controls. Further, those with anxiety disorders exhibited greater EPN in response to fearful compared to happy and neutral faces, suggesting that those with anxiety disorders may have enhanced selective attention for fearful faces [-@yoonEnhancedEarlyPosterior2016]. EPN has been observed across a variety of different tasks, inter-stimulus intervals (ISI), and stimulus presentation durations [@olofssonAffectivePictureProcessing2008], leading researchers to surmise that the EPN reflects relatively automatic processes that is observed even when processing resources are limited due to rapid presentation rates [@junghoferFleetingImagesNew2001; @schuppAttentionEmotionERP2003; @schuppEmotionalFacilitationSensory2003]. This sensitivity may index rapid affective amygdala processing of emotionally salient information [@ledouxEmotionCluesBrain1995; @morrisConsciousUnconsciousEmotional1998] as is also theorized to indicate "natural selective attention" where evaluation of image features is contingent upon affectively arousing perceptual characteristics for additional processing [@dolcosEventrelatedPotentialsEmotional2002; @schuppSelectiveProcessingBriefly2004]. Thus, it is hypothesized that highly arousing positive and negative OASIS images will elicit greater EPN compared to neutral OASIS images.

Some research has indicated that EPN is sensitive to emotion regulation. Herbert and colleagues [-@herbertNoFearNo2013] found that EPN signals were significantly attenuated during active downregulation of emotional intensity in response to pictures of fearful faces. Such effects were not found for downregulation of emotional intensity in response to happy faces [@herbertNoFearNo2013]. One study analyzed EPN differences among participants with low and high trait anxiety in an implicit emotion regulation task in response to pictures of faces [@liuImplicitEmotionRegulation2018]. The study found that implicit emotion regulation processing led to more significant decreases in behavioral negative emotion experience scores, and that these decreases in negative emotion experience scores were associated with enlarged EPN [@liuImplicitEmotionRegulation2018]. Lastly, these enlargements were observed for participants with low trait anxiety but not high grait anxiety, suggesting deficits in implicit emotion regulation among those with anxiety [@liuImplicitEmotionRegulation2018]. However, these findings are not consistent Other research has shown that implicit emotion regulation modifies an earlier EEG component, the N170, but does not modulate the EPN [@wangTemporalCourseImplicit2017]. Investigation of the relationship between EPN and explicit emotion regulation has not been thoroughly investigated, possibly due to the fact that the EPN is viewed as an index for automatic discrimination processes [@pietrekNeuromagneticIndicationDysfunctional2012] rather than higher-order cognitive strategies employed in emotion regulation. Therefore, no hypotheses were made regarding the relationship between regulation conditions and personality traits in the present study and EPN. In exploratry analyses, EPN will be subsituted for the LPP as the outcome variable in primary analyses to investigate whether the difference between regulation blocks and EPN is contingent upon personality traits pertaining to positive emotion. 

Other exploratory analyses will focus on characterizing the relationship between behavioral ratings for emotional valence (negative to positive), emotional intensity (not arousing to highly arousing), difficulty of the regulation task (easy to difficult) and EEG components of interest (i.e., LPP & EPN). Research has consistently demonstrated that LPP is augmented in response to highly arousing positively- and negatively-valenced images [@olofssonAffectivePictureProcessing2008] which are further associated with behavioral ratings [@bradleyInternationalAffectivePicture2007; @kurdiIntroducingOpenAffective2017]. Thus, a positive linear relationship between LPP and arousal ratings is hypothesized. A curvinear relationship between LPP and valence ratings, such that highly negative and positive valence ratings are associated with great LPP and neutral ratings associated with attenuated LPP, is also hypothesized. This curvilnear relationship has been observed in norming studie for the OASIS image set [@kurdiIntroducingOpenAffective2017]. Findings are inconsistent regarding the relationship between EPN and valence. Some researchers have noticed augmented EPN in response to positive and negative stimuli [@liuImplicitEmotionRegulation2018] while others have only observed valence effects for negative stimuli [@wangTemporalCourseImplicit2017]. Given that there is a body of literature supporting a relationship between EPN and emotional arousal [@olofssonAffectivePictureProcessing2008; @schuppAffectivePictureProcessing2000; @schuppAttentionEmotionERP2003] and the fact that negatively- *and* positively-valenced images are associated with heightened arousal, a curvilinear relationship between valence and EPN is also hypothesized. Following this rationale, it is also predicted that there will be a positive relationship between EPN and arousal ratings. NEXT: DIFFICULTY?

### Method 
#### Participants
54 participants were recruited for the study, 48 of which were included in analyses (*n* = 27 women, *n* = 2 non-binary). Six participants were excluded due to insufficient number of valid EEG task trials. Participants ranged in age from 18-29 (M = 19.78 years, SD = 2.03). The sample was 69.6% Caucasian, 17.4% Asian, 2.1% Black or African American, and 8.7% Biracial (2.1% declined to answer); 10.9% reported that they were Hispanic/Latino and 89.1% were not Hispanic/Latino. The study was approved by the Institutional Review Board and informed consent was provided to all participants prior to beginning the experiment. 

#### Materials and Procedure
Participants were asked to complete the trait Positive and Negative Affect Schedule (PANAS; Watson, Clark, & Tellegen, 1988) to assess for positive affectivity ($\alpha = .86$). At the beginning and end of the experiment, participants were also asked to complete the state PANAS in order to assess state affect changes over the course of the experiment ($\alpha = .86$; Watson et al., 1988). Participants also completed the Savoring Beliefs Inventory (SBI; Bryant, 2009). The SBI measures the perception of one’s ability to feel pleasure through anticipating positive outcomes ($\alpha = .87$), savoring positive moments ($\alpha = .83$), and reminiscing about past positive events ($\alpha = .86$; Bryant, 2009). Only the momentary savoring subscale was used in the following analyses, as this temporal domain was most relevant to the present hypotheses and experimental paradigm.
64-channel high-density electroencephalography (EEG) data were recorded while participants viewed seven blocks of 40 images (280 total trials). The study used 120 different Open Affective Standardized Image Set (OASIS) images [@kurdiIntroducingOpenAffective2017]. 40 of the images were positive, 40 were neutral, and 40 were negative. Previous research has shown that 40 trials is sufficient to evoke a reliable late positive potential (LPP) component [@fotiDeconstructingReappraisalDescriptions2008; @hajcakAttendingAffectAppraisal2006; @hajcakPersistenceAttentionEmotion2008; @hajcakReappraisalModulatesElectrocortical2006]. The mean normative valence ratings (on a scale of one to seven) were 5.71, 4.09, and 2.18 for positive, neutral, and negative pictures, respectively. The mean normative arousal ratings (on a scale of one to seven) were 4.46, 1.99, and 4.52, for positive, neutral, and negative pictures, respectively. Though previous studies have used the IAPS, theses means are similar to those reported in other LPP studies [@cuthbertBrainPotentialsAffective2000; @fotiDifferentiatingNeuralResponses2009; @hajcakReappraisalModulatesElectrocortical2006; @keilLargescaleNeuralCorrelates2002; @schuppAttentionEmotionERP2003].

Each block represented an experimental regulation condition: increase (positive/negative), decrease (positive/negative), and watch (positive/negative/neutral). During the increase condition, participants were instructed to appraise the picture in a way that will intensify the emotion that is elicited by looking at it. During the decrease condition, participants were asked to reduce the intensity of the emotion that is elicited by looking at the picture. When prompted to watch, participants were asked to view the picture as they would naturally. The passive “watch” blocks served as baseline conditions for LPP component analyses [@hajcakReappraisalModulatesElectrocortical2006]. A block design was selected for the proposed study because valenced images outnumber the neutral images two-to-one. The relatively rare neutral stimuli may produce a P3 if intermixed with valenced stimuli in the same block [@schuppAffectivePictureProcessing2000].Additionally, LPP signal is increased for stimuli that are percieved as incongruent within a given affective context. Thus, a neutral stimulus displayed in a series of emotional stimuli would likely evoke an enahnced LPP activity, thus decreasing effect size [@schuppAffectivePictureProcessing2000]. Further, a block design paradigm may better emulate one's natural environment. Stimuli of congruent valence are typically encountered in clusters rather than isolation [@schuppAffectivePictureProcessing2012]. Research comparing intermixed and block designs for LPP and EPN have shown comparable findings between the two approaches [@pastorAffectivePicturePerception2008; @schuppAffectivePictureProcessing2012].

First, participants completed three practice trials that consisted of 10 not used during the actual task [@hajcakReappraisalModulatesElectrocortical2006]. Participants were instructed to increase or decrease emotional arousal in response to a mixture of positive and negative images, respectively. Participants were also asked to watch a third practice trial comprised of positive, negative, and neutral images. Stimuli were presented in random order. Prior to each practice trial, participants were provided with instructions on how to regulate (increase/decrease) their affective response to the stimuli, or to simply view the stimuli [@moserIntentionalModulationEmotional2006]. Participants were shown which regulation strategy to engage in (increase, decrease, or watch) at the start of each experimental block. Once the participant was ready, an OASIS stimulus appeared for 2000 ms [@fotiDifferentiatingNeuralResponses2009; @hajcakPersistenceAttentionEmotion2008]. Following stimulus offset, a blank screen appeared for 500 ms followed by a fixation cross for 1500 ms (± 250 ms) for a total ISI of 1750 - 2250 ms. This interval is identical to other studies utilizing the IAPS and investigating LPP [@dunningSeeNoEvil2009; @hajcakMotivatedControlledAttention2009]. Stimuli within each block were presented in random order. Each block was separated by a break and presented in random order. After each experimental block, valence and arousal ratings were collected using a seven-point likert scale and the same instructions used in Kurdi, Lozano, and Banaji’s [-@kurdiIntroducingOpenAffective2017] norming study of the OASIS stimuli set. Furthermore, difficulty ratings on a seven-point likert scale were also obtained.

#### Apparatus and Physiological Recording
Scalp EEG was measured while participants completed an emotion regulation task. Participants were seated in a comfortable chair, approximately 24 inches from a 24-inch LCD monitor in a quiet, dimly lit room. Participants were monitored by a task administrator in a nearby room and received task instructions by intercom. EEG data were recorded using a Biosemi Active2 EEG system. A custom-designed Falk Minow 64-channel cap with equidistantly spaced BioSemi active Ag and AgCl electrodes was used for data collection. CMS/DRL was placed near the vertex, and two electrodes were located on the mastoid bones. After placement of the electrode cap, electrode positions were digitized. An additional electrode was placed on the inferior edge of the orbit of each eye to monitor vertical eye movements; nearby electrodes in the cap (lateral to each eye) monitored horizontal eye movements. Data was recorded with a band pass of 0 – 104 Hz at a sampling rate of 512 Hz.
The following EEG data processing steps were implemented in Brain Electrical Source Analysis software [BESA; @schergBESABrainElectric1990]. EEG data were re-referenced to the average activity of the mastoid electrodes [@hajcakAttendingAffectAppraisal2006; @hajcakReappraisalModulatesElectrocortical2006] and digitally filtered with a half-power amplifier bandpass at 0.01–30 Hz, with a cutoff attenuation of 12 dB/octave. Muscle (e.g., eye blink, eye movement) and other artifacts were removed and/or corrected via implementing automatic algorithms in BESA. Stimulus-locked averages were calculated to ascertain LPP. The data were baseline-adjusted by subtracting the average activity for 200 milliseconds (Hajcak et al., 2006) before stimulus onset. LPP activity was calculated as the average activity in the 300 – 800 ms window at Pz, P1, P2 and CPz electrode sites. The scoring window and sites were selected based upon the existing literature as well as visual inspection of the data to determine where LPP activity was maximal in the present sample. The selected scoring window and electrode sites were similar to other studies investigating LPP in similar contexts (Hajcak et al., 2006; Hajcak & Nieuwenhuis, 2006; Moser et al., 2006). The experiment was computer-administered, using E-Prime 2.0 software [@schneiderEPrimeUserGuide2002] in order to manipulate the timing and presentation of stimuli. All stimuli were presented in color and occupied the entirety of the 21-inch monitor. The viewing distance was approximately 24 in. and occupied 25°of the vertical visual angle and 30° horizontally (Cuthbert et al., 2000; Hajcak & Nieuwenhuis, 2006).

### Results
The first objective of the proposed study was to investigate the relationship between highly arousing affective vs. neutral stimuli from the OASIS and parietal cortical activity (LPP). Data below a skewness statistic of 1.0 were considered normally distributed. No variables of interest violated this threshold. Participants without valid EEG data were excluded from the following analyses (*n* = 6). No other data were missing from variables of interest.
All analyses were run in R version 3.5.0 (R Core Team, 2018). Multilevel modeling (MLM) analyses were conducted using the lme4 package [@batesFittingLinearMixedeffects2015]. Means and standard deviations of LPP activity and participant ratings (arousal, valence, and difficulty) were calculated for each of the experimental blocks (see Table 1). In order to evaluate whether the experimental blocks varied on arousal and valence, a repeated measures analysis of variance yielded significant variation among image blocks for arousal ($F(6, 270) = 25.02$, $p < .001$) and valence ($F(6, 270) = 80.43$, $p < .001$) ratings. Tukey’s HSD test was used to calculate comparisons across all blocks for arousal (see Table 2) and valence (see Table 3) ratings using the psycho package [@makowskiPsychoPackageEfficient2018]. Pearson correlations were run among psychological and physiological variables across the sample. Significant correlations were found between several variables (see Table 4). Means and standard deviations of between-subjects variables (savoring the moment, trait positive affect, and state positive affect) were also derived (see Table 4).

Before testing primary hypotheses, a null model was run to assess whether the grouping variable (participant) differed on the outcome variable (parietal cortical activity) and to estimate the degree of nonindependence in the sample. An intraclass-correlation indicated that that 56% of the total variance in LPP activity is accounted for by differences between participants’ average LPP activity. This necessitates an analytical technique, such as MLM, that accounts for non-independence. Semi-partial R^2 was calculated for model parameters to estimate relative variance explained by each predictor [@edwardsR2StatisticFixed2008; @trittIdeologicalReactivityPolitical2016].
#### Hypotheses 1a & 1b. 
MLM with variance components covariance matrices to estimate random intercepts and slopes for each participant was used to test whether increased LPP activity is associated with passively viewing highly arousing affective compared to neutral OASIS stimuli. Dummy-coded block (within subjects: neutral watch block as reference level) and mean- centered valence (within subjects) variables were included in the omnibus model to predict LPP activity while accounting for the variance attributed to the how positive or negative participants rated each block. A main effect of block type upon LPP activity was found (positive watch; $b = 1.38$, $SE = .39$, $t(244.96) = 3.52$, $p < .001$, $R^2 = .03$; negative watch; $b = 2.12$, $SE = .42$, $t(249.05) = 5.10$, $p < .001$, $R^2 = .06$). These findings indicate that passively viewing affective (positive and negative) compared to neutral OASIS images is associated with enhanced LPP activity (see Figure 4).
#### Hypothesis 2a 
The second objective was to examine the relationship between personality traits pertaining to positive emotion (i.e., positive affectivity and savoring capacity) and parietal cortical activity. MLM with variance components covariance matrices to estimate random intercepts and slopes for each participant was used to test if the relationship between LPP activity and passively viewing positive images versus neutral images varied as a function of trait positive affect. Dummy-coded block (within subjects: neutral watch block as reference level), mean-centered difficulty rating (within subjects), mean-centered trait positive affect (between subjects), and mean-centered state positive affect (between subjects) variables were included in the omnibus model. An interaction term between block and trait positive affect variables was also added to probe for a conditional relationship between block and LPP activity as a function of trait positive affect while accounting for the variance attributed to the how difficult participants rated each block and their state positive affect. Results did not indicate a significant interaction between viewing condition and positive affectivity in predicting LPP activity ($b = 0.03$, $SE = .06$, $t(262.81) = 0.50$, $p = .620$, $R^2 < .01$).
#### Hypothesis 2b
MLM with variance components covariance matrices to estimate random intercepts and slopes for each participant was used to test if the relationship between parietal cortical activity and increasing emotional intensity in response to positive images versus passively watching positive images (see Figure 5) varied as a function of momentary savoring capacity. Dummy-coded block (within subjects: positive watch block as reference level), mean- centered difficulty rating (within subjects), mean-centered savoring capacity (between subjects), and mean-centered trait positive affect (between subjects) variables were included in the omnibus model. An interaction term between the block and savoring capacity variables was added to probe for a conditional relationship between block and LPP activity as a function of momentary savoring capacity while accounting for the variance attributed to the how difficult participants rated each block and their trait positive affect. Results did not indicate a significant interaction between viewing condition and savoring capacity in predicting LPP activity ($b = 0.30$, $SE = .39$, $t(262.79) = 0.76$, $p = .445$, $R^2 < .01$).

### DISCUSSION
The present study sought to explore the OASIS as an alternative to the IAPS in psychophysiological research as well the role of personality traits in neural affective processing. This research will help introduce more up-to-date and open access materials in affective neuroscience research and devise neuroscience-informed clinical interventions to enhance positive emotion. We found that, similar to the IAPS, highly arousing positive and negative OASIS stimuli elicited augmented LPP activity. Furthermore, positive affectivity and capacity to savor the moment did not influence the relationship between passively viewing and increasing emotional intensity in response to positive images, respectively.
Results suggest that highly arousing positive and negative images are correlated with enhanced parietal cortical activity. This is a common finding in research investigating the neural time course of affective processing with the IAPS [@cuthbertBrainPotentialsAffective2000; @hajcakMotivatedControlledAttention2009; @hajcakNeuralResponseEmotional2007; @krompingerModulationsElectrophysiologicalResponse2008; @moserIntentionalModulationEmotional2006; @schuppAffectivePictureProcessing2000; @trittIdeologicalReactivityPolitical2016]. Participant rating scales in the present study indicated that passively viewing positive and negative image blocks were associated with more arousal when compared to neutral images. Passively watching negative images was associated with higher arousal ratings when compared to positive images. Passively viewing negative images was associated with valence scores that were significantly lower than neutral images, yet the difference between positive and neutral images was not significant. This suggests that negatively-valenced stimuli may have more profound effects on state manipulations of emotion than positively-valenced stimuli. Notably, these behavioral ratings did not correlate with LPP activity. This may be attributed to the fact that participant ratings likely reflect state manipulations at the end of each block while LPP may reflect arousal and/or valence in response to each image. Overall, these findings lend support to the OASIS image set being used in subsequent psychophysiological studies investigating the neural time course of affective processing. The OASIS also has several advantages over the IAPS. More specifically, it is up-to-date, spans a number of semantic categories, and is open access [@kurdiIntroducingOpenAffective2017].

Evidence of conditional relationships between regulating one’s emotion in response to affective images and LPP activity as a function of personality traits pertaining to positive emotion was not found. This is a departure from earlier fMRI research investigating correlations between neural activation in response to pleasant stimuli/happy faces and the personality trait of extraversion [@canliAmygdalaResponseHappy2002; @canliFMRIStudyPersonality2001]. This discrepancy could be due to different methods. Canli et al. (2001, 2002) utilized fMRI and presented five blocks of four pictures that were presented for 7.5 seconds each while the present study used EEG and utilized seven blocks of 40 image blocks that were presented for two seconds each. fMRI does not have the temporal resolution necessary to analyze timing in the 0 – 3000 ms time window as the present study did. Thus, it is possible that different components were being analyzed in Canli et al. (2001, 2002) and the present study. Furthermore, Canli et al. (2001) limited their sample to only women on the grounds that, “...they are more likely to report intense emotional experiences (Shields, 1991) and because they show more physiological reactivity in concordance with valence judgments than men (Lang, Greenwald, Bradley, & Hamm, 1993).” In contrast, the present study recruited participants regardless of gender in order produce more generalizable findings. Additionally, different statistical analyses were utilized in the present study compared to those reported in Canli et al. (2002, 2003). Though the language used in Canli et al. (2003) suggests a moderation analysis: “...given that amygdala activation to positive emotional scenes varies as a function of this trait...” (p. 1), closer inspection indicates that correlations between z scores for voxels in fMRI slices and personality traits were reported. This technique necessitates multiple statistical tests, inflating type-I error, and is unable to account for variance attributed to other variables. True moderation analyses, as performed in the present study, are tested in a single regression model that allows one to statistically control for effects of other variables.
There are several other noteworthy aspects of the present study. Psychology is in the midst of a “replicability crisis,” suggesting that a majority of published findings in the field may be false [@bakerHalfPsychologyStudies2015]. This is compounded by instances of scientific misconduct [@stroebeScientificMisconductMyth2012], unwillingness to share data for re-analyses [@wichertsPoorAvailabilityPsychological2006], and questionable statistical practices [@simmonsFalsepositivePsychologyUndisclosed2011]. It is incumbent upon psychological researchers to resolve these problems. To this end, hypotheses of the present study were preregistered with the Center for Open Science (link: [https://osf.io/p5ba9/](https://osf.io/p5ba9/)). Furthermore, all data and R code used for data management, analyses, and ERP visualizations are publicly available so that others may independently replicate reported results. This study is also notable for the analytical technique utilized to test main hypotheses (MLM). MLM improves upon the most commonly used technique in ERP research, repeated measures analysis of variance, in several ways: 1) MLM accepts categorical and continuous predictors, 2) researchers can use partial data in MLM analyses, and 3) more complex models can be specified using MLM. Lastly, previous studies utilizing affective stimuli and EEG utilized an experimental design that randomly presents images of intermixed valence (positive, negative, and neutral). LPP is sensitive to intrinsic affective properties of stimuli picture and the local affective context in which the picture is presented (Schupp et al., 2000). There may be overlap between neural responsivity to incongruency and psychophysiological components of interest related to a behavioral task (e.g., increasing or decreasing emotional intensity) in these randomized designs. This may introduce extraneous variance not germane to the question at hand. The present study rectifies this methodological issue by utilizing a block design where no images were presented in an affectively incongruent context. The present study contributes to the field beyond its findings through its transparency as well as its methodological and statistical rigor.
Despite the strengths and novelty of this experiment, there are limitations. The psychophysiological data collected are cross-sectional and causation cannot be inferred. While we have done our best to adhere to open science principles, software used for EEG reduction is closed source (BESA; Scherg & Berg, 1990). While we are unable to share materials or code that can replicate our data reduction analyses, we have provided step-by-step instructions that were used for data reduction. Lastly, the present study’s exclusionary criteria (only recruited participants who were right-handed, not color-blind, and learned English as a first language) and reliance on a convenience sample mostly comprised of Caucasian college students limits ability to generalize findings to a more diverse population. Future research should investigate the neural correlates of positive emotion regulation in more diverse samples. Much research on this topic (the present study included) relies on convenience samples (e.g., Hajcak & Nieuwenhuis, 2006; Kim & Hamann, 2007; Moser et al., 2006).
Research indicates that past adverse experiences may contribute to one’s capacity to savor present events [@croftTribulationsAppreciationExperiencing2014]. An interesting future line of inquiry may examine if past experiences predict certain patterns of neural activity in response to emotional stimuli. Additionally, research indicates that psychopathology influences emotion regulation and salience of emotional stimuli [@ehringEmotionRegulationVulnerability2010; @gotlibAttentionalBiasesNegative2004; @hamiltonNeuralSubstratesIncreased2008; @joormannEmotionRegulationDepression2010; @joormannEmotionRegulationDepression2014]. Future research should investigate how depression and anxiety influence neural activity in response to passively viewing and regulating one’s emotion in response to affective stimuli.
It may be that the LPP is not capturing the mechanism most relevant to savoring or positive affectivity. Thus, future research should consider utilizing different EEG methods. For example, source analysis is able to identify subcortical neural source generators of EEG activity. Considering that savoring is a form of emotion regulation, it may be related to structures implicated in metacognition, such as the ACC. Another method to consider is time-frequency analysis, which is able to simultaneously measure signals in time and frequency domains. Frontal EEG alpha band frequency asymmetry has been observed at rest in those with depression [@gotlibEEGAlphaAsymmetry1998; @keuneApproachingDysphoricMood2013; @stewartFrontalEEGAsymmetry2011; @thibodeauDepressionAnxietyResting2006], and research has also shown correlations between reductions of frontal alpha band EEG frequency and decreased depression symptomatology [@zotevCorrelationAmygdalaBOLD2016]. Considering that low positive affectivity is theorized to be a specific risk factor for depression [@clarkTripartiteModelAnxiety1991; @kendallProspectiveAssociationsLow2015; @lewinsohnPleasantActivitiesDepression1973; @raesDampeningPositiveAffect2012; @watsonTestingTripartiteModel1995; @watsonTestingTripartiteModel1995a] and related to exacerbated depressive symptomatology [@clarkTripartiteModelAnxiety1991; @davidsonAffectiveStyleAffective1998a; @watsonExtraversionPsychopathologyFacetlevel2015], it may be associated with less left frontal EEG alpha-band frequency.
This is one of the first studies to examine the neural time course of affective processing using the OASIS. Results indicate that it is an appropriate replacement for the IAPS. Future researchers would be wise to utilize the OASIS in order to facilitate comparison of results across studies and capitalize on its high quality, open access, and up-to-date stimuli. Results of the present study did not support the hypotheses that positive affectivity and capacity to savor the moment alter the relationship between passively viewing and increasing emotional intensity in response to positive images, respectively. However, future aims have been identified based on these findings, such as examining the role that past experiences/psychopathology play in neural affective processing, recruiting a more diverse sample, and utilizing different EEG methods (e.g., source analysis, time frequency analysis) to study how the neural time course of affective processing interacts with positive affectivity and savoring capacity. The study is limited by its use of cross-sectional data, precluding causal inference, and a sample predominately comprised of Caucasian college students, which limits generalizability of findings. Regardless of these limitations, the present study sets standards for open science practice, statistical analyses, and methods for future research in affective neuroscience. The present study brings attention to the often-neglected study of positive emotion and its neural correlates. Past research on affective processing has overwhelmingly focused on negative emotion. This work is useful for mitigating the effects of unpleasant emotion but may not benefit individuals in need of bolstered levels ofpositive emotion. Uncovering the biological implementations of positive emotion will be crucial for developing therapeutic and pharmacological interventions for those suffering from psychological and physiological ailments. It may also bring us a step closer to harnessing the mechanisms of wellbeing.
