# POSITIVELY MINDFUL: NEURAL CHANGES IN POSITIVE AFFECTIVE PROCESSING AFTER EIGHT WEEKS OF HEADSPACE

- reward processing in depression?
- reduced bias to positive stimuli
- emotion stroop literature?
- annie gelden work on it P3 and faces
hypotheses: blunted resposne to positive but not negative stimuliw
Outline
- Depression intro
- Emotion reactivity/dysregulation in depressive disorders (positive and negative)
  - Inability to recruit frontal systems to reduce amygdala activities during regulation, hyperactivity of frontal systems when watching (transition to ECI). No research on upregulation.
  - In EEG, ECI theory - reduced significance of stimuli with blunted LPP in response to affective stimuli. No ER research in depression       with EEG
- positive emotion regulation constructs that may be modifiable intervention targets 
- Mindfulness intro - Headspace - scalable intervention.
  - neural correlates of mindfulness, past RCT studies
  - mindfulness and emotion regulation/processing.
- present study- hypotheses

Major Depressive Disorder (MDD) is one of the most common psychological disorders [@goodwinEpidemiologyMoodDisorders2006]. 
In the United States, 17% of adults experience at least one major depressive episode during their life [@kesslerLifetimePrevalenceAgeofonset2005]. 
Depression symptoms are associated with life impairments including interpersonal relationship strain, increased likelihood of poor work performance and burnout, and decreased physical wellbeing [@drussImpairmentRoleFunctioning2009a; @kesslerPrevalenceEffectsMood2006; @lewinsohnPsychosocialFunctioningYoung2003]. 
In the United States, depression-related loss in work productivity has been estimated to exceed $36 billion [@kesslerPrevalenceEffectsMood2006]. 
Treatment outcomes for depression suggest that even after the completion of therapy, 54% of individuals relapse within two years following treatment [@vittenglReducingRelapseRecurrence2007]. 
Depression is currently a highly intractable disorder with a high rate of recurrence and relapse. 
Translational research that strives to develop a better understanding of factors that contribute to ongoing symptoms and relapse is urgently needed to develop effective treatments. 

## Emotion Dysregulation in Depression
Impaired capability to regulate negative emotions is considered a robust feature of depression. 
Broadly defined, emotion regulation refers to the psychological processes that modulate an initial emotional response [@lewisAdvancesProblemsChallenges2010] and implies that a change has occurred from initial reactivity (i.e., baseline affective response to a stimulus).
Inability to regulate negative emotion has been theorized to result in depression and anxiety [@campbell-sillsl.IncorporatingEmotionRegulation2007; @mclaughlinContributoryRoleWorry2007], and deficits in regulating emotional response to everyday events results in exacerbated periods of distress or clinical levels of psychopathology [@nolen-hoeksemaRethinkingRumination2008].
Further, Major Depressive Disorder (MDD) is characterized by sustained negative affect and impaired ability to experience positive affect [@joormannEmotionRegulationDepression2014].
MDD is marked by inability to repair negative emotion, consequently leading to compounded periods of depression [@nolen-hoeksemaRethinkingRumination2008].
Indeed, those with MDD tend to ruminate (i.e., repetitive thinking focused on one's depressive symptoms as well as implications, causes, and meanings of these symptoms; @nolen-hoeksemaRethinkingRumination2008), which increases negative affect and predicts future depressive episodes [@nolen-hoeksemaRethinkingRumination2008]. Further, there is a tendency for those with depression to use suppression as opposed to reappraisal, the former of which is a maladaptive regulation strategy that is associated with reduced wellbeing [@grossIndividualDifferencesTwo2003] and exacerbated depression symptoms [@joormannEmotionRegulationDepression2010].
While suppressing negative emotion may result in some reduction of expressive behavior (e.g., facial movement) and physiological arousal, subjective experience of negatively-valenced stimuli may be no less distressing than if one did not suppress emotion [@grossEmotionalSuppressionPhysiology1993].

Depression is also related to a response style that reduces experience of positive affect [@werner-seidlerInvestigationRelationshipPositive2013]; those who report dampening positive affect are at increased risk of experiencing future depressive symptoms [@raesDampeningPositiveAffect2012]. 
Previous emotion regulation research has predominantly focused on downregulating negative emotions to decrease sadness and negative affect and has largely overlooked the role of positive emotion regulation [@joormannExaminingEmotionRegulation2016a]. 
Yet, above and beyond other depression symptoms, anhedonia (i.e., lack of pleasure) is a hallmark feature of MDD [@americanpsychiatricassociationDiagnosticStatisticalManual2013] and may be associated with impairments in positive emotion regulation [@joormannExaminingEmotionRegulation2016a]. 
Indeed, individuals with depression report ruminating upon positive events/emotions less that those without depression, and this absence of positive rumination in large part characterizes anhedonia [@werner-seidlerInvestigationRelationshipPositive2013]. 
Anhedonia negatively impacts daily function, predicts poor treatment response, indicates risk for future depressive episodes, and shows specificity with regard to depression diagnosis [@khazanovBrighteningEffectReactions2019; @watsonSpecificityPositiveEmotional2010b]. Anhedonia involves abnormal bi-directional reactivity and regulatory affective processes including 1) positive attenuation, or hyporeactivity to positive stimuli [@bylsmaMetaanalysisEmotionalReactivity2008; @forbesNeuralSystemsPositive2005] and 2) impaired capacity to enhance or upregulate affective responses evoked by positive stimuli [@forbesNeuralSystemsPositive2005]. 
Emerging research on positive emotion dysregulation in depression indicates that impaired regulatory mechanisms may diminish the frequency, duration, intensity, and quality of positive emotions, including difficulties anticipating, initiating, sustaining, or upregulating positive stimuli and experiences [@forbesNeuralSystemsPositive2005; @joormannExaminingEmotionRegulation2016a; @liuSelectionImplementationEmotion2017].

Experiencing positive emotions is paramount to deriving vitality from daily lived experiences.
Positive emotions are associated with a range of beneficial intertwined psychological and physical outcomes including longevity, reduced incidents of stroke, improved sleep quality, larger social networks, increased prosocial behavior, lower cortisol levels, and increased endogenous opioids and oxytocin [@pressmanPositiveAffectHealth2019; @siltonRegulatingPositiveEmotions2020a].
However, only limited research has focused on understanding positive emotion regulation within the context of depression.
Moving forward, a new focus on developing evidence-based strategies to target impairments in positive emotion regulation in depression could be critical to improving the low treatment outcome rate in depression.

Research has shown that those with remitted depression exhibit augmented limbic system activity in response to negative images and attenuated limbic system activity in response to positive images compared to never-depressed participants [@thomasInteractionHistoryDepression2011]. 
Additionally, participants with MDD have demonstrated enhanced activity in the dorsolateral prefrontal cortex (PFC), a region associated with cognitive control and emotion regulation, when viewing positive images compared to healthy controls [@demenescuNeuralCorrelatesPerception2011]. 
This difference in neural activation, the authors suggest, is indicative of suppression of positive emotion  [@demenescuNeuralCorrelatesPerception2011].
Those with mood disorders tend to exhibit decreased activation in a fronto-parietal network (recruiting posterior cingulate cortex, dorsomedial prefrontal cortex, angular gyri, and left ventrolateral prefrontal cortex) compared to those without mood disorders [@pico-perezEmotionRegulationMood2017; @zilverstandNeuroimagingCognitiveReappraisal2017] when downregulating emotional responsivity to aversive stimuli.
Hypoactivity of these regions may be indicative of ineffective management of attentional and inhibitory resources [@pico-perezEmotionRegulationMood2017].
Notably, this pattern of results held when controlling for the effects of particular subgroups of patients [i.e., women, adolescents, patients on medication; @pico-perezEmotionRegulationMood2017].
To the authors' knowledge, no research has investigated the neural timecourse (via EEG) of emotion upregulation in those with mood disorders.

Abler et al (2010) - amygdala hyperactivity as a trait abnormality in those with depression in response to affective stimuli. Supporting this, Drevets et al. (1992) suggested that amygdala hyperactivity might be a trait abnormality in familial pure depressive disease since it is also evident between depressive episodes. Elevated amygdala activity in depressed patients in remission has also been shown to predict symptom relapse (Bremner et al., 1997). Our results therefore add evidence to the hypothesized role of trait amygdala hyperactivity as a predictor of depressive symptoms and potentially related habitual emotion-regulation styles.

overall picture with MDD - dysregulated regulation systems. Hyperactivity of frontal systems during watch conditions and hypoactivity during regulation conditions - not consonant with regulatory goal.

## Neural Affective Processing in Depression
Affective disorders such as MDD and dysthymia are associated with abnormal emotional reactivity as indexed by the late positive potential (LPP) in response to affective stimuli [@grunewaldAttenuatedLPPEmotional2019]. LPP is a sustained positive slow wave observed starting as early as 300 ms following stimuli onset and is as an established index of evaluative congruency, valence, and arousal in response to visual stimuli [@olofssonAffectivePictureProcessing2008].
LPP over the centroparietal cortex is augmented in the presence of unpleasant and pleasant compared to neutral images [@cuthbertBrainPotentialsAffective2000; @dillonDissociationEventrelatedPotentials2006; @fotiDeconstructingReappraisalDescriptions2008; @hajcakAttendingAffectAppraisal2006; @hajcakReappraisalModulatesElectrocortical2006; @hajcakTemporalDynamicsEmotion2007; @keilLargescaleNeuralCorrelates2002; @moserIntentionalModulationEmotional2006; @olofssonAffectivePictureProcessing2008; @schuppEmotionalFacilitationSensory2003] and is most pronounced for images that are rated as highly arousing [@bradleyInternationalAffectivePicture2007].
LPP has been theorized to reflect activation of a brain network engaged in processing affective visual stimuli, including subcortical structures, particularly the amygdala [@bradleyInternationalAffectivePicture2007; @cuthbertBrainPotentialsAffective2000; @keilLargescaleNeuralCorrelates2002; @olofssonAffectivePictureProcessing2008; @schuppEmotionalFacilitationSensory2003].
Research has demonstrated attenuated LPP in response to both unpleasant and pleasant affective stimuli [@fotiReducedElectrocorticalResponse2010; @kayserEventrelatedPotentialsERPs2000; @macnamaraDiagnosticSymptombasedPredictors2016].
This pattern of findings is largely consistent with an emotion context insensitivity [ECI; @rottenbergEmotionContextInsensitivity2005] model of MDD, suggesting that depression is linked with overall deficits in emotional reactivity. 
A meta-analysis showed that attenuated emotional reactivity (across self-report, behavioral, and physiological measures) was present for those with MDD compared to healthy controls [@bylsmaMetaanalysisEmotionalReactivity2008a].
Of note, reductions in emotional reactivity were stronger for positive compared to negative stimuli, which is partially consistent with positive attenuation model of emotional reactivity in MDD [i.e., emotional reactivity is selectively diminished for positive emotions; @clarkTemperamentPersonalityMood].
Indeed, those with MDD show attenuated startle reflex in response to positive, negative, and neutral visual affective stimuli [e.g., @dichterEarlyLateonsetStartle2004], less facial electromyography activity in response to negative and positive faces [@wexlerDecreasedPerceptualSensitivity1994], and dulled self-report emotional experiences in response to negative and positive film clips [@rottenbergSadnessAmusementReactivity2002].
Of particular interest is a study conducted by Weinberg and colleagues [-@weinbergDepressionReducedNeural2016] found that, in a sample with diagnoses of MDD and anxiety disorders, a diagnosis of MDD was uniquely associated with attenuated LPP in response to rewarding visual stimuli while an anxiety disorder was not. 
The aforementioned study did not demonstrate an association with MDD diagnosis and reduced LPP in response to threatening stimuli, though this correlation was in the same direction as the association with rewarding stimuli [@weinbergDepressionReducedNeural2016].
A follow up study found that those with MDD and previous suicide attempts had blunted LPP in response to rewarding and threatening stimuli [@weinbergDecreasedNeuralResponse2017].
Thus, it was hypothesized that reductions in depression symptoms in the current study would lead to enhanced LPP reactivity in response to passively viewing both positive and negative stimuli.
Results from Foti (2010) suggest that early neural responsivity is intact in those with MDD (as indexed by enhanced vertex parietal potential in response to fearful/angry faces compared to neutral).
However, those with MDD did not show modulation in LPP in response to affective faces. 

## Savoring strategies upregulate positive emotions in depression. 
Savoring-based regulatory strategies are the most commonly used strategies implemented to sustain and upregulate positive emotions [@heiyBackBasicsNaturalistic2014; @liuSelectionImplementationEmotion2017]. First coined by Bryant (1989), savoring refers to the capacity “to attend to, appreciate, and enhance the positive experience in one’s life” [@bryantSavoringNewModel2007].
People initiate savoring responses in reaction to a positive event or feeling as a way to maintain, intensify, or prolong the initial positive experience [@bryantSavoringNewModel2007].
While savoring, one may eagerly anticipate future positive experiences, focus on ongoing positive experiences as they occur in the present moment, or reminisce about past positive experiences.
Regardless of the temporal focus, savoring processes upregulate positive emotions in the present moment. 
Savoring strategies that amplify positive emotions are associated with greater frequency of positive affect [@smithNurturingCapacitySavor2014] and the capacity to savor is positively associated with extraversion, self-esteem, happiness, and life satisfaction [@bryantSavoringBeliefsInventory2003a].
Correspondingly, lack of savoring capacity is inversely correlated with anhedonia, depression, hopelessness, and neuroticism [@bryantSavoringBeliefsInventory2003a], indicating that the capability to upregulate positive emotions likely involves modifiable processes that are vulnerable to change in depression [@siltonRegulatingPositiveEmotions2020a]. 

With specific relevance to depression, studies aimed at enhancing savoring capacity show that enriching any of the three temporal domains of savoring (reminiscing, savoring the moment, or anticipating) is associated with increased frequency and intensity of positive affect, and decreased negative affect [@bryantDimensionsSubjectiveMental1984; @bryantSavoringNewModel2007].
Training on momentary positive emotion regulation (i.e., memory building, expressing positive emotions) resulted in decreased self-reported depression symptoms when compared to a control group after two weeks [@hurleyResultsStudyIncrease2012].
A savoring intervention study that was conducted in older adults showed that diminished dampening of positive emotions was related to decreased depression symptoms [@smithEffectsSavoringIntervention2017]. Savoring may improve the capacity to recognize and enjoy positive moments, even during difficult times [@smithEffectsSavoringIntervention2017].
Positive self-attributions for recent positive events have been associated with attenuated depression symptoms and enhanced positive affect following positive events in a sample of college-aged women [@mcmakinPositiveAffectStimulation2011].
Increased attention to positive stimuli is a candidate psychological mechanism through which positive emotion regulation strategies are theorized to mitigate depression symptoms [@carlPositiveEmotionRegulation2013; @joormannExaminingEmotionRegulation2016a]. 

## Mindfulness-based interventions may increase capacity for positive emotion regulation in individuals with depression. 
While savoring and mindfulness are not analogous, there may be some overlapping conceptual aspects [@bryantAppreciatingLifeMidst2015; @bryantSavoringNewModel2007; @hurleyResultsStudyIncrease2012]. 
Mindfulness meditation practices and mindfulness-based interventions emphasize the importance of cultivating non-judgmental attention and awareness in the present moment [@guHowMindfulnessbasedCognitive2015a], which may help enhance the capability to savor the moment. 
Mindfulness meditation is theorized to enhance the capacity for and experience of positive emotions [@garlandMindfulnessBroadensAwareness2015a; @wielgoszMindfulnessMeditationPsychopathology2019a] and ultimately promote wellbeing [@dahlReconstructingDeconstructingSelf2015a], as well as broaden cognitive scope which in turn bolsters the capacity for savoring [@garlandMindfulnessBroadensAwareness2015a]. 
Mindfulness meditation practices may modify positive valence systems through enhanced emotion awareness, modulations in emotional reactivity, increased use of cognitive reappraisal, and alterations in reward processes [@wielgoszMindfulnessMeditationPsychopathology2019a].
Along with increasing attention and awareness toward positive experiences as they occur, positive reappraisal may be a key emotion regulation mechanism related to mindfulness meditation practice that reduces stress and depression symptoms [@garlandMindfulnessBroadensAwareness2015a].

Headspace is a top-rated mindfulness app per psyberguide.org [@AppGuidePsyberGuide].
It is also scalable and cost-effective. Additionally, out of 23 commonly used mindfulness-based mental health apps, researchers awarded Headspace with the highest rating on the Mobile Application Rating Scale, which assesses app engagement, functionality, aesthetics, information quality, and subjective satisfaction [@maniReviewEvaluationMindfulnessBased2015].
Since the onset of this study, Headspace has provided our study team with free three-month Headspace access codes for study participants and they also share all user-data for study participants.
Headspace otherwise provides no other financial support for this research.
The present study aims to advance our understanding of self-report wellbeing and neurophysiological outcomes that index changes in depression and positive emotion regulation following an eight-week trial of Headspace.

## Establishing the neural correlates of positive emotion regulation. 
Previous affective neuroscience research rarely focused on reaction and response to positive emotion; thus, we presently have a minimal understanding regarding the neural correlates associated with positive emotion, which remains a critical area of research to attend to moving forward [@siltonRegulatingPositiveEmotions2020a]. 

Our research team conducted an electroencephalography (EEG) study to validate and establish the emotion regulation task used in the present study.This research was fundamental to improving our understanding of the temporal course of the neural correlates of positive emotion reactivity and regulation. We pre-registered this previous EEG study, and consistent with open science practices, we will make the data publicly available (OSF link: [https://osf.io/p5ba9](https://osf.io/pb5ba9)). This research focused on two key event-related potential (ERP) components which provide information about the temporal course of neural activity involved in processing affective stimuli: the early posterior negativity (EPN) and the late positive potential (LPP) in response to positive emotion reactivity and regulation. The EPN represents an early categorization of affective stimuli whereas the LPP is indicative of a later integrated conceptual analysis [@frankHemodynamicElectrocorticalReactivity2019]. LPP is an established index of emotional arousal in response to visual stimuli [@hajcakEventrelatedPotentialsEmotion2010; @sabatinelliParallelAmygdalaInferotemporal2005] and is theorized to index a visual cortical/amygdala pathway that is involved in evaluating the affective salience of a stimuli34. Increased LPP has been associated with increased subjective reports of emotional arousal [@fotiDeconstructingReappraisalDescriptions2008]. Therefore, we expected that the capability to flexibly modulate emotional intensity in response to positive stimuli would be indexed by LPP, which would be associated with increased positive emotion regulation capacity (per self-report). 

Primary study aim: We will evaluate the hypothesis that an eight-week app-based mindfulness meditation intervention will modify neural correlates of positive emotion regulation for individuals with depression symptoms. Building upon emerging research from my laboratory that characterizes patterns of brain activity associated with positive emotion regulation and savoring the moment [@kahrilasSavoringMomentLinkreviseandresubmit], the proposed project will evaluate whether an eight-week Headspace mindfulness intervention modifies the neural correlates of positive emotion regulation in individuals with depression symptoms. Specifically, the proposed study will evaluate whether the capability to modulate emotional intensity in response to positive stimuli (as indexed by EPN and LPP) will be increased for emerging adults with depression following eight weeks of Headspace use. Illustrating proof of concept and feasibility for the proposed research, our preliminary analyses demonstrate that Headspace reduces depression symptoms and increases momentary savoring capacity [@conleyBenefitsMobileMindfulness2019; @siltonPsychologicalNeuralCorrelates2018]. 
Significance

Cultivating the capacity to experience positive emotions via upregulating the experience associated with positive stimuli and moments as they occur is critical to psychological and physical health outcomes. The proposed study will examine indices of neural (EEG) function and their association with positive emotion regulation capabilities in order to identify potential mechanisms. This broad aim is consistent with the National Institute of Mental Health (NIMH) Research Domain Criteria (RDoC) initiative which encourages researchers to integrate across units of analysis in order to better characterize dimensional perspectives on human behavior. Identifying modifiable psychological mechanisms associated with positive emotion regulation is critical to advancing evidence-based therapeutic approaches that promote societal health and wellbeing, particularly in the present milieu of rapidly increasing rates of depression and anxiety disorders [@worldhealthorganizationWorldHealthStatistics2014]. As such, this research has the potential to inform interventions to enhance physical wellbeing and psychological vitality in individuals with medical and psychological disorders, such as depression, postpartum depression, and pain disorders. Furthermore, this project will provide opportunities to mentor graduate and undergraduate research assistants. Through mentoring in human neuroscience research, students will build a broader skill set involving data science, critical thinking, development of innovative ideas, project management, and communication abilities that will prepare them for successful careers in psychological or health sciences.

## Mindfulness and emotion regulation
### neuroscience
The neural mechanisms of mindfulness remain elusive. 
Studies that have investigated neural activation during meditative states found increased activation in regions linked with attention and emotion regulatory states, such as PFC and anterior cingulate cortex (ACC), along with reduced amygdala activation [@cahnMeditationStatesTraits2006; @holzelStressReductionCorrelates2010; @lutzMindfulnessEmotionRegulation2014].
A meta-analysis indicated that ERP studies investigating effects of medication are marred by, "...lack of methodological sophistication, no replication of critical conditions, and inconsistency of task and study populations" [@cahnMeditationStatesTraits2006, p. 196].
However, it appears that the P300 component is influenced by meditation practice [@cahnMeditationStatesTraits2006], which may index output from a common system as LPP that indicates the neural timecourse of stimulus significance [see @hajcakSignificanceSignificanceEmpirical2020 for a review].


Rather, the P300/LPP is elicited by motivationally significant stimuli, whether they are targets of the task, emotionally evocative, or idiographic for a specific individual. Thus, the P300 and LPP may reflect output from a common system that tracks the time-course of stimulus significance.


<!-- From Grunewald: -->
<!-- Affective disorders such as major depression and dysthy- mic disorder are associated with abnormalities in the LPP. Depressed individuals have been shown to exhibit reduced LPPs in response to unpleasant emotional stimuli (Foti et al. 2010; Kayser et al. 2000; MacNamara et al. 2016a). Interestingly, Weinberg et al. (2016) found dramatically re- duced LPP to rewarding and threatening images in adults with onset of depression in adolescence, but not in those with onset in adult age. Studies investigating children and adolescents focused on youth at risk of depressive disorders. Kujawa et al. (2012a) identified the time course and scalp distribution of the LPP in response to emotional faces in young children of mothers with a history of depression. These children failed to show differentiation between emotional and neutral faces in the early occipital LPP. In another study, Nelson et al. (2015) examined adolescent girls with a parental risk for depression who were found to show blunted LPP to pleasant, unpleasant and also neutral pictures, suggesting more extensive blunting and motivational withdrawal. Investigating a sample of youth with anxiety disorders, Kujawa et al. (2015) found reduced LPP associated with depressive symptoms. Hence, studies with risk samples suggest that patterns of electrocortical reactivity to emotional stimuli may be associated with vulnerability to depressive disorders. All in all, the findings of reduced LPPs in adults with depressive disorders and youth at risk of depression are in line with the ECI hypothesis (Rottenberg et al. 2005). -->

<!-- From MacNamara 2016a: -->
<!-- Substantial evidence supports the ECI model of depression (e.g., for a review, see Bylsma, Morris, & Rottenberg, 2007). For instance, individuals with MDD report less subjectively experienced affect when viewing sad or amusing film clips (Rottenberg et al., 2005; Rottenberg, Kasch, Gross, & Gotlib, 2002). MDD has also been associated with reduced emotional modulation of the startle reflex (Dichter & Tomarken, 2008; Dichter, Tomarken, Shelton, & Sutton, 2004; Taylor-Clift, Morris, Rottenberg, & Kovacs, 2011) and with decreased electromyographic facial responding when viewing emotional pictures as compared to healthy adults (HAs; Wexler, Levenson, Warrenburg, & Price, 1994) and patients with other disorders (Gehricke & Shapiro, 2000). Of the studies described above, only two ensured that depressed participants were free from comorbid GAD (Gehricke & Shapiro, 2000; Wexler et al., 1994). Further, only one of the studies described above (Taylor- Clift et al., 2011) examined how comorbid depression modifies affective responding in GAD and other anxiety disorders. In their study, Taylor-Clift and colleagues (2011) found that emotional modulation of the startle reflex was preserved in individuals with anxiety who were free from depression, but was blunted among those with both anxiety and depression, suggesting that the pattern of emotion processing in comorbid anxiety-depression may most closely resemble that observed in depression (i.e., context-insensitivity). -->

<!-- more macnamara -->
<!-- Neurobiological measures may be particularly useful in identifying common and distinct mechanisms within and across disorders (Cuthbert, 2014; Morris & Cuthbert, 2012). For instance, event-related potentials (ERPs) can be used to provide a highly sensitive measure of the processing of emotional stimuli. The late positive potential (LPP) is a positive-going, central-parietal ERP that begins by 300 ms following stimulus onset and is larger for more arousing stimuli – e.g., both pleasant and unpleasant compared to neutral pictures and words (Cuthbert, Schupp, Bradley, Birbaumer, & Lang, 2000; Dillon, Cooper, Grent-‘t-Jong, Woldoff, & LaBar, 2006; Foti, Hajcak, & Dien, 2009; Schupp et al., 2000). Functionally, the LPP is believed to reflect increased and elaborated attention to stimuli that have been deemed motivationally salient (M. M. Bradley, 2009). In addition to tracking categorical differences in picture emotionality, the LPP is also sensitive to more fine-grained differences in the motivational salience of stimuli. For instance, the LPP is larger to food pictures in participants deprived of food (Stockburger, Schmälzle, Flaisch, Bublatzky, & Schupp, 2009) and to personally salient stimuli such as photographs of one's own relatives or loved ones (Grasso & Simons, 2011; Vico, Guerra, Robles, Vila, & Anllo-Vento, 2010). Therefore, the LPP appears to be modulated by individual differences in the perceived salience of stimuli, which may make it an ideal measure for assessing attention to unpleasant stimulus content in anxiety and depression. -->

<!-- work utilizing the LPP has tended to support the ECI view of depression (for a review, see Proudfit, Bress, Foti, Kujawa, & Klein, 2015). For instance, Foti and colleagues (2010) found that individuals with “pure” MDD (i.e., free from comorbid GAD) showed reduced LPPs to threatening (i.e., angry and fearful) faces compared to HAs. Similar results were observed by Kayser and colleagues (Kayser, Bruder, Tenke, Stewart, & Quitkin, 2000), who, in a study focused on disgust-processing, found that individuals with MDD and/or dysthymia (comorbid diagnoses not reported) showed reduced LPPs to pictures of dermatological disease. There is also evidence to suggest that blunted LPPs might serve as a biomarker of risk for depression in individuals who have not yet developed symptoms: children without depression, whose mothers have a history of depression have been found to exhibit reduced LPPs to emotional faces, when compared to children who are also depression-free and without maternal history of depression (Kujawa, Hajcak, Torpey, Kim, & Klein, 2012; see also Nelson, Perlman, Hajcak, Klein, & Kotov, 2015). -->

<!-- Together, the work described above raises the possibility that GAD and MDD might be distinguished by opposing affective processes – GAD with larger LPPs and MDD with smaller LPPs. Moreover, these opposing processes could be obscured by high levels of comorbidity frequently observed between these disorders. That is, increased response to unpleasant stimuli in GAD could be concealed by comorbid depression (B. P. Bradley et al., 1995), and vice-versa. However, few studies have examined the processing of unpleasant stimuli simultaneously in individuals diagnosed with GAD or MDD, as well as those with comorbid GAD and MDD (but see Taylor-Clift et al., 2011). -->

# maybe for hypothesis section
Related, research has indicated that those who use antecedent-focused emotion regulation strategies (reappraisal) while viewing a negatively-valenced film reported less subjective negative emotional response than those instructed to use a response-focused emotion regulation strategy (suppression) or passively watch [@grossAntecedentandResponsefocusedEmotion1998; @grossEmotionalSuppressionPhysiology1993]. Reappraisal and suppression strategies successfully led to decreases in behavioral signs of emotion, measured by coding participants’ behavioral responses (i.e., facial behavioral and upper body movement) in response to the films, but reappraisal was not associated with elevations in physiological responses (i.e., finger pulse activity, finger temperature, skin conductance, & heart rate). Emotional suppression, on the other hand, led to increases in physiological response on several indices [@grossAntecedentandResponsefocusedEmotion1998]. Overall, results suggest that antecedent-focused emotion regulation strategies are a more effective means of experiencing less negative emotional states and, similar to response-focused strategies, successfully decrease behavioral reactions. This, coupled with augmented physiological responses associated with response-focused strategies, may suggest that antecedent-focused emotion regulation is a more effective, or adaptive, means of regulating one’s emotions [@grossAntecedentandResponsefocusedEmotion1998; @grossIndividualDifferencesTwo2003]. These findings also support the association between adverse health consequences and maladaptive emotion regulation strategies, as habitual suppression of emotion may be correlated with chronically elevated physiological arousal [@grossEmergingFieldEmotion1998; @hintonMechanismsEfficacyCBT2009; @jorgensenElevatedBloodPressure1996].

Indeed, it has been proposed that individuals who experience episodes of depression differ from their non-depressed counterparts not so much in their initial responses to negative events but in their responses to the ensuing affect and, specifically, in their ability to repair or regulate negative emotion, which results in longer episodes of sadness and depressed mood - can tie this into state manipulations with behavioral ratings in in paradigm.

Research investigating affective neural processing in those with MDD 
