# CHAPTER ONE: INTRODUCTION

```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## Positive emotion dysregulation in depressive disorders

Major Depressive Disorder (MDD) is one of the most common psychological disorders [@goodwinEpidemiologyMoodDisorders2006]. In the United States, 17% of adults experience at least one major depressive episode during their life [@kesslerLifetimePrevalenceAgeofonset2005]. Depression symptoms are associated with life impairments including interpersonal relationship strain, increased likelihood of poor work performance and burnout, and decreased physical wellbeing [@drussImpairmentRoleFunctioning2009a; @kesslerPrevalenceEffectsMood2006; @lewinsohnPsychosocialFunctioningYoung2003]. In the United States, depression-related loss in work productivity has been estimated to exceed $36 billion [@kesslerPrevalenceEffectsMood2006]. Treatment outcomes for depression suggest that even after the completion of therapy, 54% of individuals relapse within two years following treatment [@vittenglReducingRelapseRecurrence2007]. Depression is currently a highly intractable disorder with a high rate of recurrence and relapse. Translational research that strives to develop a better understanding of factors that contribute to ongoing symptoms and relapse is urgently needed to develop effective treatments. 

Impaired capability to regulate negative emotions is considered a robust feature of depression. Previous emotion regulation research has predominantly focused on downregulating negative emotions to decrease sadness and negative affect and has largely overlooked the role of positive emotion regulation [@joormannExaminingEmotionRegulation2016a]. Yet, above and beyond other depression symptoms, anhedonia (i.e., lack of pleasure) is a hallmark feature of MDD [@americanpsychiatricassociationDiagnosticStatisticalManual2013], and may be associated with impairments in positive emotion regulation [@joormannExaminingEmotionRegulation2016a]. Anhedonia negatively impacts daily function, predicts poor treatment response, indicates risk for future depressive episodes, and shows specificity with regard to depression diagnosis [@khazanovBrighteningEffectReactions2019; @watsonSpecificityPositiveEmotional2010b]. Anhedonia involves abnormal bi-directional reactivity and regulatory affective processes including 1) positive attenuation, or hyporeactivity to positive stimuli [@bylsmaMetaanalysisEmotionalReactivity2008; @forbesNeuralSystemsPositive2005] and 2) impaired capability to enhance or upregulate affective responses evoked by positive stimuli [@forbesNeuralSystemsPositive2005]. Broadly defined, emotion regulation refers to the psychological processes that modulate an initial emotional response [@lewisAdvancesProblemsChallenges2010] and implies that a change has occurred from initial reactivity (i.e., baseline affective response to a stimulus). Emerging research on positive emotion dysregulation in depression indicates that impaired regulatory mechanisms may diminish the frequency, duration, intensity, and quality of positive emotions, including difficulties anticipating, initiating, sustaining, or upregulating positive stimuli and experiences [@forbesNeuralSystemsPositive2005; @joormannExaminingEmotionRegulation2016a; @liuSelectionImplementationEmotion2017].

Experiencing positive emotions is paramount to deriving vitality from daily lived experiences. Positive emotions are associated with a range of beneficial intertwined psychological and physical outcomes including longevity, reduced incidents of stroke, improved sleep quality, larger social networks, increased prosocial behavior, lower cortisol levels, and increased endogenous opioids and oxytocin [@siltonRegulatingPositiveEmotions2020a]. However, only limited research has focused on understanding positive emotion regulation within the context of depression. Moving forward, a new focus on developing evidence-based strategies to target impairments in positive emotion regulation in depression could be critical to improving the low treatment outcome rate in depression.

## Savoring strategies upregulate positive emotions in depression. 

Savoring-based regulatory strategies are the most commonly used strategies implemented to sustain and upregulate positive emotions [@heiyBackBasicsNaturalistic2014; @liuSelectionImplementationEmotion2017]. First coined by Bryant (1989), savoring refers to the capacity “to attend to, appreciate, and enhance the positive experience in one’s life” [@bryantSavoringNewModel2007]. People initiate savoring responses in reaction to a positive event or feeling as a way to maintain, intensify, or prolong the initial positive experience [@bryantSavoringNewModel2007]. While savoring, one may eagerly anticipate future positive experiences, focus on ongoing positive experiences as they occur in the present moment, or reminisce about past positive experiences. Regardless of the temporal focus, savoring processes upregulate positive emotions in the present moment. Savoring strategies that amplify positive emotions are associated with greater frequency of positive affect [@smithNurturingCapacitySavor2014] and the capacity to savor is positively associated with extraversion, self-esteem, happiness, and life satisfaction [@bryantSavoringBeliefsInventory2003a]. Correspondingly, lack of savoring capacity is inversely correlated with anhedonia, depression, hopelessness, and neuroticism [@bryantSavoringBeliefsInventory2003a], indicating that the capability to upregulate positive emotions likely involves modifiable processes that are vulnerable to change in depression [@siltonRegulatingPositiveEmotions2020a]. 

With specific relevance to depression, studies aimed at enhancing savoring capacity show that enriching any of the three temporal domains of savoring (reminiscing, savoring the moment, or anticipating) is associated with increased frequency and intensity of positive affect, and decreased negative affect [@bryantDimensionsSubjectiveMental1984; @bryantSavoringNewModel2007]. Training on momentary positive emotion regulation (i.e., memory building, expressing positive emotions) resulted in decreased self-reported depression symptoms when compared to a control group after two weeks [@hurleyResultsStudyIncrease2012]. A savoring intervention study that was conducted in older adults showed that diminished dampening of positive emotions was related to decreased depression symptoms [@smithEffectsSavoringIntervention2017]. Savoring may improve the capability to recognize and enjoy positive moments, even during difficult times [@smithEffectsSavoringIntervention2017]. Positive self-attributions for recent positive events have been associated with attenuated depression symptoms and enhanced positive affect following positive events in a sample of college-aged women [@mcmakinPositiveAffectStimulation2011]. Increased attention to positive stimuli is a candidate psychological mechanism through which positive emotion regulation strategies are theorized to mitigate depression symptoms [@carlPositiveEmotionRegulation2013; @joormannExaminingEmotionRegulation2016a]. 

## Mindfulness-based interventions may increase capacity for positive emotion regulation in individuals with depression. 

While savoring and mindfulness are not analogous, there may be some overlapping conceptual aspects [@bryantAppreciatingLifeMidst2015; @bryantSavoringNewModel2007; @hurleyResultsStudyIncrease2012]. Mindfulness meditation practices and mindfulness-based interventions emphasize the importance of cultivating non-judgmental attention and awareness in the present moment [@guHowMindfulnessbasedCognitive2015a], which may help enhance the capability to savor the moment. Mindfulness meditation is theorized to enhance the capacity for and experience of positive emotions [@garlandMindfulnessBroadensAwareness2015a; @wielgoszMindfulnessMeditationPsychopathology2019a] and ultimately promote wellbeing [@dahlReconstructingDeconstructingSelf2015a], as well as broaden cognitive scope which in turn bolsters the capacity for savoring [@garlandMindfulnessBroadensAwareness2015a]. Mindfulness meditation practices may modify positive valence systems through enhanced emotion awareness, modulations in emotional reactivity, increased use of cognitive reappraisal, and alterations in reward processes [@wielgoszMindfulnessMeditationPsychopathology2019a]. Along with increasing attention and awareness toward positive experiences as they occur, positive reappraisal may be a key emotion regulation mechanism related to mindfulness meditation practice that reduces stress and depression symptoms [@garlandMindfulnessBroadensAwareness2015a].

Headspace is the top-rated mindfulness app per psyberguide.org. It is also scalable and cost-effective. Additionally, out of 23 commonly used mindfulness-based mental health apps, researchers awarded Headspace with the highest rating on the Mobile Application Rating Scale, which assesses app engagement, functionality, aesthetics, information quality, and subjective satisfaction [@maniReviewEvaluationMindfulnessBased2015]. Since the onset of this study, Headspace has provided our study team with free three-month Headspace access codes for study participants and they also share all user-data for study participants. Headspace otherwise provides no other financial support for this research. The present study aims to advance our understanding of self-report wellbeing and neurophysiological outcomes that index changes in depression and positive emotion regulation following an eight-week trial of Headspace.

## Establishing the neural correlates of positive emotion regulation. 

Previous affective neuroscience research rarely focused on reaction and response to positive emotion; thus, we presently have a minimal understanding regarding the neural correlates associated with positive emotion regulation, which remains a critical area of research to attend to moving forward15. Our research team conducted an electroencephalography (EEG) study to validate and establish the emotion regulation task used in the present study. This research was fundamental to improving our understanding of the temporal course of the neural correlates of positive emotion reactivity and regulation. We pre-registered this previous EEG study, and consistent with open science practices, we will make the data publicly available (OSF link: [https://osf.io/p5ba9](https://osf.io/pb5ba9)). This research focused on two key event-related potential (ERP) components which provide information about the temporal course of neural activity involved in processing affective stimuli: the early posterior negativity (EPN) and the late positive potential (LPP) in response to positive emotion reactivity and regulation. The EPN represents an early categorization of affective stimuli whereas the LPP is indicative of a later integrated conceptual analysis [@frankHemodynamicElectrocorticalReactivity2019]. LPP is an established index of emotional arousal in response to visual stimuli [@hajcakEventrelatedPotentialsEmotion2010; @sabatinelliParallelAmygdalaInferotemporal2005] and is theorized to index a visual cortical/amygdala pathway that is involved in evaluating the affective salience of a stimuli34. Increased LPP has been associated with increased subjective reports of emotional arousal [@fotiDeconstructingReappraisalDescriptions2008]. Therefore, we expected that the capability to flexibly modulate emotional intensity in response to positive stimuli would be indexed by LPP, which would be associated with increased positive emotion regulation capacity (per self-report). 

Primary study aim: We will evaluate the hypothesis that an eight-week app-based mindfulness meditation intervention will modify neural correlates of positive emotion regulation for individuals with depression symptoms. Building upon emerging research from my laboratory that characterizes patterns of brain activity associated with positive emotion regulation and savoring the moment [@kahrilasSavoringMomentLinkreviseandresubmit], the proposed project will evaluate whether an eight-week Headspace mindfulness intervention modifies the neural correlates of positive emotion regulation in individuals with depression symptoms. Specifically, the proposed study will evaluate whether the capability to modulate emotional intensity in response to positive stimuli (as indexed by EPN and LPP) will be increased for emerging adults with depression following eight weeks of Headspace use. Illustrating proof of concept and feasibility for the proposed research, our preliminary analyses demonstrate that Headspace reduces depression symptoms and increases momentary savoring capacity [@conleyBenefitsMobileMindfulness2019; @siltonPsychologicalNeuralCorrelates2018]. 
Significance

Cultivating the capacity to experience positive emotions via upregulating the experience associated with positive stimuli and moments as they occur is critical to psychological and physical health outcomes. The proposed study will examine indices of neural (EEG) function and their association with positive emotion regulation capabilities in order to identify potential mechanisms. This broad aim is consistent with the National Institute of Mental Health (NIMH) Research Domain Criteria (RDoC) initiative which encourages researchers to integrate across units of analysis in order to better characterize dimensional perspectives on human behavior. Identifying modifiable psychological mechanisms associated with positive emotion regulation is critical to advancing evidence-based therapeutic approaches that promote societal health and wellbeing, particularly in the present milieu of rapidly increasing rates of depression and anxiety disorders [@worldhealthorganizationWorldHealthStatistics2014]. As such, this research has the potential to inform interventions to enhance physical wellbeing and psychological vitality in individuals with medical and psychological disorders, such as depression, postpartum depression, and pain disorders. Furthermore, this project will provide opportunities to mentor graduate and undergraduate research assistants. Through mentoring in human neuroscience research, students will build a broader skill set involving data science, critical thinking, development of innovative ideas, project management, and communication abilities that will prepare them for successful careers in psychological or health sciences.
